### ISSUE TITLE
build failed on linux-6.2

### ISSUE THREAD

**Issue by sbwml** [ntop/PF_RING#861]
version: PF_RING 8.4 Release
gcc: 11.2.0

```
  CC [M]  /redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.o
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c: In function 'ring_bind':
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:5560:21: error: invalid application of 'sizeof' to incomplete type 'char[]'
 5560 |     char name[sizeof(sa->sa_data)+1];
      |                     ^
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:5565:37: error: invalid application of 'sizeof' to incomplete type 'char[]'
 5565 |     memcpy(name, sa->sa_data, sizeof(sa->sa_data));
      |                                     ^
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:5560:10: warning: unused variable 'name' [-Wunused-variable]
 5560 |     char name[sizeof(sa->sa_data)+1];
      |          ^~~~
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c: In function 'ring_getsockopt':
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:7960:26: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 7960 |         char *dev_addr = pfr->ring_dev->dev->dev_addr;
      |                          ^~~
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c: In function 'hash_pkt_cluster':
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:3882:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
 3882 |     if(l3_proto == IPPROTO_TCP)
      |       ^
/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.4.0/kernel/pf_ring.c:3889:3: note: here
 3889 |   case cluster_per_flow_2_tuple:
      |   ^~~~
```

**Comment by cardigliano** [comment]
@sbwml 6.2 is not yet supported, we will do our best to support it asap. What OS are you running?

**Comment by sbwml** [comment]
> @sbwml 6.2 is not yet supported, we will do our best to support it asap. What OS are you running?

openwrt 😜😜😜

**Comment by sbwml** [comment]
> > @sbwml 6.2 is not yet supported, we will do our best to support it asap. What OS are you running?
> 
> openwrt 😜😜😜

Cross-compilation for openwrt

**Comment by BKPepe** [comment]
For OpenWrt, it was fixed with custom patch from @Ansuel, in this commit - https://github.com/openwrt/packages/commit/2f86385ff56c4e204133dfeef9e0ec1cada6ba56.

**Comment by sbwml** [comment]
> For OpenWrt, it was fixed with custom patch from @Ansuel, in this commit - [openwrt/packages@2f86385](https://github.com/openwrt/packages/commit/2f86385ff56c4e204133dfeef9e0ec1cada6ba56).

It fixes builds on linux-6.1 kernels, but still fails on Linux 6.2 & 6.3.

I tried it like this (openwrt-22.03.5 nanopi-r5s kernel 6.3 ):
```shell
rm -rf feeds/packages/libs/libpfring
svn export https://github.com/openwrt/packages/branches/master/libs/libpfring feeds/packages/libs/libpfring

make package/feeds/packages/libpfring/compile V=s
```

complete output:
```
[sbwml@debian openwrt]$ make package/feeds/packages/libpfring/compile V=s
make[2]: Entering directory '/home/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/openwrt/scripts/config'
make[1]: Entering directory '/home/openwrt'
make[2]: Entering directory '/home/openwrt/package/libs/toolchain'
Makefile:735: WARNING: skipping libgomp -- package has no install section
echo "libc" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libatomic" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.14#0.04#0.16
make[2]: Entering directory '/home/openwrt/package/libs/libpcap'
echo "libpcap" >> /home/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/libpcap.default.install
make[2]: Leaving directory '/home/openwrt/package/libs/libpcap'
time: package/libs/libpcap/compile#0.13#0.05#0.15
make[2]: Entering directory '/home/openwrt/feeds/packages/libs/libpfring'
mkdir -p /home/openwrt/dl
SHELL= flock /home/openwrt/tmp/.libpfring-8.0.0.tar.gz.flock -c '  	/home/openwrt/scripts/download.pl "/home/openwrt/dl" "libpfring-8.0.0.tar.gz" "8e733899b736fe2536ef785b2b7d719abe652297fe7fe3a03fc495a87a9b6e82" "" "https://codeload.github.com/ntop/PF_RING/tar.gz/8.0.0?"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/ntop/PF_RING/tar.gz/8.0.0?/libpfring-8.0.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.3M    0 22.3M    0     0  4684k      0 --:--:--  0:00:04 --:--:-- 4807k
touch /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.prepared_1fa873cb91a12d77ceadaa5efb0ada78_6664517399ebbbc92a37c5bb081b5c53_check
. /home/openwrt/include/shell.sh; gzip -dc /home/openwrt/dl/libpfring-8.0.0.tar.gz | tar -C /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0

Applying ./patches/0001-fix-cross-compiling.patch using plaintext: 
patching file userland/configure

Applying ./patches/100-fix-compilation-warning.patch using plaintext: 
patching file kernel/pf_ring.c
touch /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.prepared_1fa873cb91a12d77ceadaa5efb0ada78_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.configured_*
rm -f /home/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.libpfring_installed
(cd /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/userland/; if [ -x ./configure ]; then find /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/ -name config.guess | xargs -r chmod u+w; find /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/ -name config.guess | xargs -r -n1 cp --remove-destination /home/openwrt/scripts/config.guess; find /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/ -name config.sub | xargs -r chmod u+w; find /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/ -name config.sub | xargs -r -n1 cp --remove-destination /home/openwrt/scripts/config.sub; AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Ofast -funsafe-math-optimizations -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections -pipe -march=armv8.2-a+crypto+crc -mcpu=cortex-a55+crypto+crc -mtune=cortex-a55 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0=PF_RING-8.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CFLAGS="-Ofast -funsafe-math-optimizations -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections -pipe -march=armv8.2-a+crypto+crc -mcpu=cortex-a55+crypto+crc -mtune=cortex-a55 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0=PF_RING-8.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Ofast -funsafe-math-optimizations -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections -pipe -march=armv8.2-a+crypto+crc -mcpu=cortex-a55+crypto+crc -mtune=cortex-a55 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0=PF_RING-8.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/usr/include -I/home/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/include/fortify -I/home/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/include " LDFLAGS="-L/home/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/usr/lib -L/home/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/lib -znow -zrelro "  MACHINE="aarch64" ac_cv_lib_nl_3_nl_socket_alloc=no  ./configure --target=aarch64-openwrt-linux --host=aarch64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
configure: WARNING: unrecognized options: --disable-nls
configure: loading site script /home/openwrt/include/site/aarch64
checking for aarch64-openwrt-linux-gcc... aarch64-openwrt-linux-musl-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether aarch64-openwrt-linux-musl-gcc accepts -g... yes
checking for aarch64-openwrt-linux-musl-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... aarch64-openwrt-linux-musl-gcc -E
checking for grep that handles long lines and -e... /home/openwrt/staging_dir/host/bin/grep
checking for egrep... /home/openwrt/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking linux/net_tstamp.h usability... yes
checking linux/net_tstamp.h presence... yes
checking for linux/net_tstamp.h... yes
checking librdi.h usability... no
checking librdi.h presence... no
checking for librdi.h... no
cc1: error: unknown value 'native' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-r
checking for clock_gettime in -lrt... yes
checking for nl_handle_alloc in -lnl... no
checking for dlopen, dlsym in -ldl... yes
checking for nl_socket_alloc in -lnl-3... (cached) no
checking PF_RING AF_XDP support... no
configure: creating ./config.status
config.status: creating lib/Makefile
config.status: creating lib/pfring_config
config.status: creating examples/Makefile
config.status: creating examples_zc/Makefile
config.status: creating examples_ft/Makefile
config.status: creating c++/Makefile
config.status: creating nbpf/Makefile
config.status: creating wireshark/extcap/Makefile
config.status: creating lib/config.h
configure: WARNING: unrecognized options: --disable-nls
touch /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.built
touch /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.built_check
make -C "/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.3.1" KERNEL_DIR="/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.3.1" ARCH="arm64" CROSS_COMPILE="aarch64-openwrt-linux-musl-" M="/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel" EXTRA_CFLAGS=" -I/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel" modules
make[3]: Entering directory '/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.3.1'
  CC [M]  /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.o
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_proc_open':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:1158:48: error: implicit declaration of function 'PDE_DATA'; did you mean 'NODE_DATA'? [-Werror=implicit-function-declaration]
 1158 |   return single_open(file, ring_proc_get_info, PDE_DATA(inode));
      |                                                ^~~~~~~~
      |                                                NODE_DATA
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:1158:48: warning: passing argument 3 of 'single_open' makes pointer from integer without a cast [-Wint-conversion]
 1158 |   return single_open(file, ring_proc_get_info, PDE_DATA(inode));
      |                                                ^~~~~~~~~~~~~~~
      |                                                |
      |                                                int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:193,
                 from ./include/linux/netdevice.h:38,
                 from ./include/linux/rtnetlink.h:7,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:84:
./include/linux/seq_file.h:166:68: note: expected 'void *' but argument is of type 'int'
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'match_filtering_rule':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:2896:25: error: storage size of 'state' isn't known
 2896 |         struct ts_state state;
      |                         ^~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:2914:17: error: implicit declaration of function 'textsearch_find_continuous' [-Werror=implicit-function-declaration]
 2914 |           rc = (textsearch_find_continuous
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:2896:25: warning: unused variable 'state' [-Wunused-variable]
 2896 |         struct ts_state state;
      |                         ^~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'free_filtering_rule':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:3176:5: error: implicit declaration of function 'textsearch_destroy' [-Werror=implicit-function-declaration]
 3176 |     textsearch_destroy(entry->pattern[i]);
      |     ^~~~~~~~~~~~~~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'add_sw_filtering_rule_element':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:3387:28: error: implicit declaration of function 'textsearch_prepare' [-Werror=implicit-function-declaration]
 3387 |       rule->pattern[idx] = textsearch_prepare("bm"      /* Boyer-Moore */
      |                            ^~~~~~~~~~~~~~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:3391:47: error: 'TS_AUTOLOAD' undeclared (first use in this function)
 3391 |                                               TS_AUTOLOAD
      |                                               ^~~~~~~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:3391:47: note: each undeclared identifier is reported only once for each function it appears in
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_proc_virtual_filtering_open':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4625:70: warning: passing argument 3 of 'single_open' makes pointer from integer without a cast [-Wint-conversion]
 4625 |   return single_open(file, ring_proc_virtual_filtering_dev_get_info, PDE_DATA(inode));
      |                                                                      ^~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:193,
                 from ./include/linux/netdevice.h:38,
                 from ./include/linux/rtnetlink.h:7,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:84:
./include/linux/seq_file.h:166:68: note: expected 'void *' but argument is of type 'int'
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
In file included from ./include/linux/byteorder/little_endian.h:5,
                 from ./arch/arm64/include/uapi/asm/byteorder.h:23,
                 from ./include/asm-generic/bitops/le.h:6,
                 from ./arch/arm64/include/asm/bitops.h:28,
                 from ./include/linux/bitops.h:68,
                 from ./arch/arm64/include/asm/cache.h:39,
                 from ./include/linux/cache.h:6,
                 from ./include/linux/time.h:5,
                 from ./arch/arm64/include/asm/stat.h:12,
                 from ./include/linux/stat.h:6,
                 from ./include/linux/module.h:13,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:79:
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'allocate_extra_dma_memory':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4876:7: error: implicit declaration of function 'pci_map_single'; did you mean 'dma_map_single'? [-Werror=implicit-function-declaration]
 4876 |       pci_map_single(to_pci_dev(dma_memory->hwdev), slot,
      |       ^~~~~~~~~~~~~~
./include/uapi/linux/byteorder/little_endian.h:32:51: note: in definition of macro '__cpu_to_le64'
   32 | #define __cpu_to_le64(x) ((__force __le64)(__u64)(x))
      |                                                   ^
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4875:31: note: in expansion of macro 'cpu_to_le64'
 4875 |     dma_memory->dma_addr[i] = cpu_to_le64(
      |                               ^~~~~~~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4878:22: error: 'PCI_DMA_BIDIRECTIONAL' undeclared (first use in this function); did you mean 'DMA_BIDIRECTIONAL'?
 4878 |                      PCI_DMA_BIDIRECTIONAL));
      |                      ^~~~~~~~~~~~~~~~~~~~~
./include/uapi/linux/byteorder/little_endian.h:32:51: note: in definition of macro '__cpu_to_le64'
   32 | #define __cpu_to_le64(x) ((__force __le64)(__u64)(x))
      |                                                   ^
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4875:31: note: in expansion of macro 'cpu_to_le64'
 4875 |     dma_memory->dma_addr[i] = cpu_to_le64(
      |                               ^~~~~~~~~~~
In file included from ./include/linux/skbuff.h:28,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:83:
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'free_extra_dma_memory':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:4901:26: error: 'PCI_DMA_BIDIRECTIONAL' undeclared (first use in this function); did you mean 'DMA_BIDIRECTIONAL'?
 4901 |                          PCI_DMA_BIDIRECTIONAL);
      |                          ^~~~~~~~~~~~~~~~~~~~~
./include/linux/dma-mapping.h:412:70: note: in definition of macro 'dma_unmap_single'
  412 | #define dma_unmap_single(d, a, s, r) dma_unmap_single_attrs(d, a, s, r, 0)
      |                                                                      ^
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_bind':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5608:19: error: invalid application of 'sizeof' to incomplete type 'char[]'
 5608 |   char name[sizeof(sa->sa_data)+1];
      |                   ^
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5620:35: error: invalid application of 'sizeof' to incomplete type 'char[]'
 5620 |   memcpy(name, sa->sa_data, sizeof(sa->sa_data));
      |                                   ^
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5608:8: warning: unused variable 'name' [-Wunused-variable]
 5608 |   char name[sizeof(sa->sa_data)+1];
      |        ^~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'do_memory_mmap':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5638:17: error: assignment of read-only member 'vm_flags'
 5638 |   vma->vm_flags |= flags;
      |                 ^~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'pf_ring_inject_packet_to_stack':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5869:9: error: implicit declaration of function 'netif_rx_ni'; did you mean 'netif_rx'? [-Werror=implicit-function-declaration]
 5869 |   err = netif_rx_ni(skb);
      |         ^~~~~~~~~~~
      |         netif_rx
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_proc_stats_open':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:6721:50: warning: passing argument 3 of 'single_open' makes pointer from integer without a cast [-Wint-conversion]
 6721 |   return single_open(file, ring_proc_stats_read, PDE_DATA(inode));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  |
      |                                                  int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:193,
                 from ./include/linux/netdevice.h:38,
                 from ./include/linux/rtnetlink.h:7,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:84:
./include/linux/seq_file.h:166:68: note: expected 'void *' but argument is of type 'int'
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_getsockopt':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:7904:26: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 7904 |         char *dev_addr = pfr->ring_dev->dev->dev_addr;
      |                          ^~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_proc_dev_open':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:8334:52: warning: passing argument 3 of 'single_open' makes pointer from integer without a cast [-Wint-conversion]
 8334 |   return single_open(file, ring_proc_dev_get_info, PDE_DATA(inode));
      |                                                    ^~~~~~~~~~~~~~~
      |                                                    |
      |                                                    int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:193,
                 from ./include/linux/netdevice.h:38,
                 from ./include/linux/rtnetlink.h:7,
                 from /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:84:
./include/linux/seq_file.h:166:68: note: expected 'void *' but argument is of type 'int'
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c: In function 'ring_bind':
/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.c:5628:1: error: control reaches end of non-void function [-Werror=return-type]
 5628 | }
      | ^
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:252: /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel/pf_ring.o] Error 1
make[3]: *** [Makefile:2028: /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/kernel] Error 2
make[3]: Leaving directory '/home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.3.1'
make[2]: *** [Makefile:92: /home/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/PF_RING-8.0.0/.built] Error 2
make[2]: Leaving directory '/home/openwrt/feeds/packages/libs/libpfring'
time: package/feeds/packages/libpfring/compile#2.56#1.79#8.11
    ERROR: package/feeds/packages/libpfring failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/libpfring/compile] Error 1
make[1]: Leaving directory '/home/openwrt'
make: *** [/home/openwrt/include/toplevel.mk:230: package/feeds/packages/libpfring/compile] Error 2
```

**Comment by sbwml** [comment]
It builds well on Linux 6.1, and I'm using this patch: https://github.com/openwrt/packages/pull/19653/commits/f7f865a5fba086ad80e71e1a7654bbf46070761a

Eventually I got it https://kmod.cooluc.com/6.1.27-1-0cb9a42d218f903ddce38174c1b012fb/kmod-pf-ring_6.1.27+8.2.0-1_aarch64_generic.ipk

----------
But as long as the kernel version is greater than 6.2, it will not build correctly.

**Comment by cardigliano** [comment]
We pushed a patch set to support latest kernels. Please reopen if there are still compilation issues (please use dev on latest kernels).
