### ISSUE TITLE
[9.2.0] libpfring.a contains __isoc23_* symbols from glibc 2.38+, breaking userland build on RHEL/Rocky 9 (glibc 2.34)

### ISSUE THREAD

**Issue by psdjc** [ntop/PF_RING#1025]
## Summary

When building PF_RING 9.2.0 userland on RHEL/Rocky/AlmaLinux 9 (glibc 2.34), the tcpdump configure step fails at `checking for pcap_loop` because `libpfring.a` contains undefined references to `__isoc23_sscanf`, `__isoc23_strtol`, and `__isoc23_strtoll`. These symbols only exist in glibc 2.38 and later, so the link cannot be resolved on systems with older glibc, breaking the entire userland build chain.

## Environment

- OS: Rocky Linux 9.7
- Kernel: `5.14.0-611.11.1.el9_7.x86_64`
- glibc: 2.34
- gcc: 11.5.0 (Red Hat 11.5.0-11), default `__STDC_VERSION__ 201710L` (C17)
- PF_RING: tag `9.2.0`

## Reproduction Steps

```bash
git clone --branch 9.2.0 --depth 1 https://github.com/ntop/PF_RING.git
cd PF_RING/userland/lib && ./configure && make && sudo make install
cd ../libpcap && ./configure && make && sudo make install
cd ../tcpdump && ./configure --prefix=/opt/pf_ring
```

The `tcpdump` configure step fails:

```
checking for pcap_loop... no
configure: error: This is a bug, please follow the guidelines in CONTRIBUTING.md...
```

## Root Cause

`config.log` shows that the `pcap_loop` link test fails because of unresolved symbols inside `libpfring.a`:

```
/usr/bin/ld: ../lib/libpfring.a(pfring_ft_table.o): in function `getifaddr':
pfring_ft_table.c:(.text+0xb7a): undefined reference to `__isoc23_sscanf'
/usr/bin/ld: pfring_ft_table.c:(.text+0xc73): undefined reference to `__isoc23_sscanf'
/usr/bin/ld: pfring_ft_table.c:(.text+0x127f): undefined reference to `__isoc23_sscanf'
/usr/bin/ld: pfring_ft_table.c:(.text+0x47f1): undefined reference to `__isoc23_strtol'
/usr/bin/ld: pfring_ft_table.c:(.text+0x4b85): undefined reference to `__isoc23_strtoll'
... (many more)
collect2: error: ld returned 1 exit status
```

Confirming the symbols are referenced:

```
$ nm userland/lib/libpfring.a | grep isoc23
                 U __isoc23_sscanf
                 U __isoc23_strtol
                 U __isoc23_strtoll
```

`__isoc23_*` symbols are produced by glibc 2.38+ headers when `sscanf`/`strtol`/`strtoll` are compiled in C23 mode (`-std=c23`/`-std=gnu23`) or when `__GLIBC_USE(C2X_STRTOL)` is enabled. They do not exist in glibc 2.34, so ld cannot resolve them on RHEL 9.

The contaminated objects originate from the pre-built FT archives committed to the repository:

```
userland/lib/libs/libpfring_ft_x86_64.a
userland/lib/libs/libpfring_ft_x86_64_core-avx2.a
userland/lib/libs/libpfring_ft_x86_64_corei7-avx.a
userland/lib/libs/libpfring_ft_x86_64_corei7.a
userland/lib/libs/libpfring_ft_x86_64_dl.a
... (and aarch64 variants)
```

These are extracted by the `extract_pfring_ft_lib` rule in `userland/lib/Makefile.in` and merged into `libpfring.a`. Because they are shipped pre-compiled, `make clean && make` cannot regenerate them — the `__isoc23_*` references are baked in regardless of the user's build environment.

The local toolchain is not the culprit: gcc 11.5.0 on this system uses C17 by default and produces no `__isoc23_*` references when compiling against glibc 2.34. Rebuilding everything else from source does not help, since the FT archives are never re-compiled.

## Impact

This blocks the entire userland build pipeline (`libpcap` links fine but produces a `libpcap.so` with the same unresolved references, and `tcpdump` configure cannot pass `pcap_loop`). Any downstream application linking against `libpfring` (e.g., custom Suricata/Zeek builds) is also affected.

Affected distributions include all currently-supported RHEL 9 and derivatives:

- RHEL 9.x (glibc 2.34) — supported until 2032
- Rocky Linux 9.x
- AlmaLinux 9.x
- Oracle Linux 9.x
- CentOS Stream 9

## Suggested Fix

Rebuild and re-commit the pre-built FT archives in `userland/lib/libs/` from a build environment that does not produce `__isoc23_*` symbol redirects. Options:

1. Build on a host with glibc < 2.38 (any RHEL/Rocky/Alma 9, Ubuntu 22.04, Debian 12, etc.)
2. Build with `-std=gnu11` (or any pre-C23 standard)
3. Build with `-D__GLIBC_USE_C2X_STRTOL=0` to suppress the redirects

Option 1 or 2 would ensure the resulting archives work on both old and new glibc systems. RHEL 9 will be supported until 2032, so glibc 2.34 compatibility is a long-term concern, not a transitional one.

## Workaround

For users hitting this issue, a temporary workaround is to build a small shim library defining `__isoc23_*` symbols as wrappers around the standard variants, install it system-wide, and link it in via `LIBS="-lisoc23shim"` during configure of libpcap and tcpdump. Happy to share details if useful, but obviously this is not a proper fix.

## Additional Context

- glibc 2.38 was released August 2023.
- Distributions shipping glibc 2.38+: Fedora 39+, Ubuntu 24.04+, Debian 13+.
- It would be helpful to know from which PF_RING release the FT archives started showing this issue, so users can identify a known-good fallback tag.

Thanks for maintaining PF_RING!

**Comment by swtar** [comment]
你好，邮件已收到！

**Comment by cardigliano** [comment]
Libraries have been recompiled on Ubuntu 22 with glibc 2.35, please pull the 9.2 or dev branch and let me know. Thank you.

**Comment by psdjc** [comment]
Confirmed fixed on 9.2.0 on Rocky Linux 9.7 (glibc 2.34).

`nm userland/lib/libpfring.a | grep isoc23` returns no output, the entire userland (libpfring, libpcap, tcpdump) builds cleanly without any workaround, and tcpdump configure now passes `checking for pcap_loop... yes`.

PF_RING kernel module loads correctly, and packet capture is fully working — Suricata and Zeek are receiving traffic as expected.

Thanks for the very fast turnaround! Closing this issue.
