### ISSUE TITLE
PF_RING 6.6.0 fails to build with CentOS 7.4

### ISSUE THREAD

**Issue by lobotmcj** [ntop/PF_RING#270]
Using the 6.6.0 release tarball (I do not have the option of building with yum from ntop repo):
+ Builds just fine with 7.3 (3.10.0-514.el7.x86_64)
+ Update to 7.4 and restart
```
yum check-update
yum update
init 6
```
+ Now at CentOS 7.4.1708 with kernel 3.10.0-693.el7.x86_64
+ Attempt to make PF_RING 6.6.0 again
```
cd /tmp/PF_RING-6.6.0
make clean
make
```
+ Errors:
```
 cd e1000e/e1000e-3.2.7.1-zc/src; make
make[3]: Entering directory `/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src'
make -C /lib/modules/3.10.0-693.el7.x86_64/build SUBDIRS=/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src modules
make[4]: Entering directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
  CC [M]  /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:32:0,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/kcompat.h:5159:20: error: redefinition of ‘csum_replace_by_diff’
 static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
                    ^
In file included from include/linux/skbuff.h:30:0,
                 from include/linux/if_ether.h:23,
                 from include/uapi/linux/ethtool.h:18,
                 from include/linux/ethtool.h:17,
                 from include/linux/netdevice.h:43,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:31:
include/net/checksum.h:110:20: note: previous definition of ‘csum_replace_by_diff’ was here
 static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
                    ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:32:0,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/kcompat.h:5192:19: error: redefinition of ‘pci_request_io_regions’
 static inline int pci_request_io_regions(struct pci_dev *pdev, const char *name)
                   ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:27:0:
include/linux/pci.h:1425:1: note: previous definition of ‘pci_request_io_regions’ was here
 pci_request_io_regions(struct pci_dev *pdev, const char *name)
 ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:32:0,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/kcompat.h:5200:20: error: redefinition of ‘pci_release_io_regions’
 static inline void pci_release_io_regions(struct pci_dev *pdev)
                    ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:27:0:
include/linux/pci.h:1432:1: note: previous definition of ‘pci_release_io_regions’ was here
 pci_release_io_regions(struct pci_dev *pdev)
 ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:32:0,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/kcompat.h:5208:1: error: redefinition of ‘pci_request_mem_regions’
 pci_request_mem_regions(struct pci_dev *pdev, const char *name)
 ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:27:0:
include/linux/pci.h:1439:1: note: previous definition of ‘pci_request_mem_regions’ was here
 pci_request_mem_regions(struct pci_dev *pdev, const char *name)
 ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:32:0,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/kcompat.h:5216:20: error: redefinition of ‘pci_release_mem_regions’
 static inline void pci_release_mem_regions(struct pci_dev *pdev)
                    ^
In file included from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:27:0:
include/linux/pci.h:1446:1: note: previous definition of ‘pci_release_mem_regions’ was here
 pci_release_mem_regions(struct pci_dev *pdev)
 ^
In file included from include/linux/kernel.h:13:0,
                 from include/linux/cache.h:4,
                 from include/linux/time.h:4,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:24:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c: In function ‘e1000e_dump’:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:265:25: error: ‘struct net_device’ has no member named ‘trans_start’
    netdev->state, netdev->trans_start, netdev->last_rx);
                         ^
include/linux/printk.h:228:34: note: in definition of macro ‘pr_info’
  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
                                  ^
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c: In function ‘e1000_xmit_frame’:
/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:7016:8: error: ‘struct net_device’ has no member named ‘trans_start’
  netdev->trans_start = jiffies;
        ^
make[5]: *** [/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o] Error 1
make[4]: *** [_module_/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src] Error 2
make[4]: Leaving directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
make[3]: *** [default] Error 2
make[3]: Leaving directory `/tmp/PF_RING-6.6.0/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/PF_RING-6.6.0/drivers/intel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/PF_RING-6.6.0/drivers'
make: *** [all] Error 2
```
+ Please advise. Thanks!

**Comment by lobotmcj** [comment]
looks like #249 had similar issue, even after moving from 6.4.1 to 6.6.0 (though the 6.6.0 error log was posted after the issue was closed)

**Comment by lobotmcj** [comment]
looks like fixed in https://github.com/ntop/PF_RING/commit/ee54df37464a427db39dc278f7828d9e2a2d1e3f
