### ISSUE TITLE
elrepo-kernel-ml + pf_ring 6.3.0-546 + centos 7 = unknown symbol sk_[de]attach_filter

### ISSUE THREAD

**Issue by leleobhz** [ntop/PF_RING#91]
Hello!

I'm having a trouble with PF_RING within CentOS 7 + Kernel-ML. It used to work well with 4.5.0 from Mainline Elrepo Kernel, but not with 4.5.2, as shown above:

```
 root ▶ sa-eqnx2-paris ▶ SSH ▶ usr ❯ src ▶ # ▶ LANG=C yum install pfring-dkms                           
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.globo.com
 * elrepo: ftp.nluug.nl
 * elrepo-kernel: ftp.nluug.nl
 * epel: mirror.globo.com
 * extras: mirror.globo.com
 * updates: mirror.globo.com
Resolving Dependencies
--> Running transaction check
---> Package pfring-dkms.noarch 0:6.3.0-546 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================
 Package                   Arch                 Version                 Repository                 Size
========================================================================================================
Installing:
 pfring-dkms               noarch               6.3.0-546               ntop-noarch                79 k

Transaction Summary
========================================================================================================
Install  1 Package

Total download size: 79 k
Installed size: 367 k
Is this ok [y/d/N]: y
Downloading packages:
pfring-dkms-6.3.0-546.noarch.rpm                                                 |  79 kB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
pfring-6.3.0-546.x86_64 has missing requires of pfring-dkms = ('0', '6.3.0', None)
  Installing : pfring-dkms-6.3.0-546.noarch                                                         1/1 
WARNING: /usr/lib64/dkms/common.postinst does not exist.
Loading new pfring-6.3.0 DKMS files...
Building for 4.5.2-1.el7.elrepo.x86_64
Building initial module for 4.5.2-1.el7.elrepo.x86_64
Done.

pf_ring:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.5.2-1.el7.elrepo.x86_64/extra/
Adding any weak-modules
depmod: WARNING: /lib/modules/4.5.2-1.el7.elrepo.x86_64/extra/pf_ring.ko needs unknown symbol sk_attach_filter
depmod: WARNING: /lib/modules/4.5.2-1.el7.elrepo.x86_64/extra/pf_ring.ko needs unknown symbol sk_detach_filter

depmod...

DKMS: install completed.
  Verifying  : pfring-dkms-6.3.0-546.noarch                                                         1/1 

Installed:
  pfring-dkms.noarch 0:6.3.0-546                                                                        

Complete!

 root ▶ sa-eqnx2-paris ▶ SSH ▶ usr ❯ src ▶ # ▶ modinfo pf_ring
filename:       /lib/modules/4.5.2-1.el7.elrepo.x86_64/extra/pf_ring.ko
alias:          net-pf-27
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
srcversion:     A6C80FA1765E7C2A67E5266
depends:        
vermagic:       4.5.2-1.el7.elrepo.x86_64 SMP mod_unload modversions 
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           transparent_mode:(deprecated) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)

 root ▶ sa-eqnx2-paris ▶ SSH ▶ usr ❯ src ▶ # ▶ ls -lahd /usr/src/linux
lrwxrwxrwx. 1 root root 42 Abr 28 11:53 /usr/src/linux -> /usr/src/kernels/4.5.2-1.el7.elrepo.x86_64

 root ▶ sa-eqnx2-paris ▶ SSH ▶ usr ❯ src ▶ # ▶ modprobe pf_ring
modprobe: ERROR: could not insert 'pf_ring': Unknown symbol in module, or unknown parameter (see dmesg)
 root ▶ sa-eqnx2-paris ▶ SSH ▶ usr ❯ src ▶ # ▶ dmesg | tail -n2
[352734.535458] pf_ring: Unknown symbol sk_attach_filter (err 0)
[352734.535486] pf_ring: Unknown symbol sk_detach_filter (err 0)

```

I tried by myself change the conditional in line 7514 to "#if 1", but it forces compilation errors. So, I dont have too much knowledge to try to fix this.

What is happening and what/how we can fix this issue?

Thanks!

**Comment by leleobhz** [comment]
Also reported at https://elrepo.org/bugs/view.php?id=646

**Comment by cardigliano** [comment]
Thank you for opening the ticket, we will fix this asap (please note this is not high priority as we support standard kernels while you are using 4.5 from kernel-ml)

Alfredo

**Comment by leleobhz** [comment]
@cardigliano  - thanks for you awnser. This used to work in kernel 4.5.0 and now don't work in 4.5.2, what is weird. There is something I can do until a definitive fix get released? Also, I remember the 4.5.2 kernel is considered stable by kernel.org.

**Comment by michael-pp** [comment]
@cardigliano I'm having the same issue on Ubuntu server 16.04 on kernel **4.4.0-22**
(on 4.4.0-21 it works fine)

**Comment by cardigliano** [comment]
Commit ddcd6fb76d327f293877a0bb58600d0e73bc3241 should fix this, new packages soon.
