### ISSUE TITLE
RHEL 8.3 and Zero Copy Drivers Compatibility

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#674]
We recently upgraded our systems to RHEL 8.3:

Red Hat Enterprise Linux release 8.3 (Ootpa)
Kernel: 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Fri Oct 16 13:36:46 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Versions (installing from https://packages.ntop.org/centos/) :

pfring                   x86_64            7.9.0-3273
pfring-dkms          noarch            7.9.0-3273 
pfring-drivers-zc-dkms      noarch                 7.9.0-3273                         
e1000e-zc                         noarch                 3.4.0.2.3273-dkms                   
i40e-zc                              noarch                 2.4.6.3273-dkms                      
igb-zc                                noarch                 5.3.5.18.3273-dkms                  
ixgbe-zc                             noarch                 5.5.3.3273-dkms                     
ixgbevf-zc                          noarch                 4.5.1.3273-dkms

All the ZC drivers won't install (from dnf) and give the same error:

Installing       : ixgbe-zc-5.5.3.3273-dkms.noarch                                                                              
Running scriptlet: ixgbe-zc-5.5.3.3273-dkms.noarch                                                                              
Loading new ixgbe-zc-5.5.3.3273 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.3273/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.3273-dkms.noarch) scriptlet failed, exit status 10
Error in POSTIN scriptlet in rpm package ixgbe-zc

Including the make.log here.

[make.log](https://github.com/ntop/PF_RING/files/5546593/make.log)

**Comment by cardigliano** [comment]
@Arislen I pushed a fix to compile the ixgbe driver on your kernel, please update and let me know

**Comment by Arislen** [comment]
Still having errors. All the drivers had the same error not just the ixgbe one. The ixgbe one now has a different error than the res
t.

(output of dnf update)
                                      
Loading new ixgbevf-zc-4.5.1.3278 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbevf-zc/4.5.1.3278/build/make.log for more information.
warning: %post(ixgbevf-zc-4.5.1.3278-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbevf-zc
  Installing       : ixgbe-zc-5.5.3.3278-dkms.noarch                                                                              2/6
  Running scriptlet: ixgbe-zc-5.5.3.3278-dkms.noarch                                                                              2/6
Loading new ixgbe-zc-5.5.3.3278 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.3278/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.3278-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbe-zc
  Installing       : igb-zc-5.3.5.18.3278-dkms.noarch                                                                             3/6
  Running scriptlet: igb-zc-5.3.5.18.3278-dkms.noarch                                                                             3/6
Loading new igb-zc-5.3.5.18.3278 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/igb-zc/5.3.5.18.3278/build/make.log for more information.
warning: %post(igb-zc-5.3.5.18.3278-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package igb-zc
  Installing       : i40e-zc-2.4.6.3278-dkms.noarch                                                                               4/6
  Running scriptlet: i40e-zc-2.4.6.3278-dkms.noarch                                                                               4/6
Loading new i40e-zc-2.4.6.3278 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/i40e-zc/2.4.6.3278/build/make.log for more information.
warning: %post(i40e-zc-2.4.6.3278-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package i40e-zc
  Installing       : e1000e-zc-3.4.0.2.3278-dkms.noarch                                                                           5/6
  Running scriptlet: e1000e-zc-3.4.0.2.3278-dkms.noarch                                                                           5/6
Loading new e1000e-zc-3.4.0.2.3278 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.4.0.2.3278/build/make.log for more information.
warning: %post(e1000e-zc-3.4.0.2.3278-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc
  Installing       : pfring-drivers-zc-dkms-7.9.0-3278.noarch                                                                     6/6
  Running scriptlet: pfring-drivers-zc-dkms-7.9.0-3278.noarch                                                                     6/6
  Verifying        : e1000e-zc-3.4.0.2.3278-dkms.noarch                                                                           1/6
  Verifying        : i40e-zc-2.4.6.3278-dkms.noarch                                                                               2/6
  Verifying        : igb-zc-5.3.5.18.3278-dkms.noarch                                                                             3/6
  Verifying        : ixgbe-zc-5.5.3.3278-dkms.noarch                                                                              4/6
  Verifying        : ixgbevf-zc-4.5.1.3278-dkms.noarch                                                                            5/6
  Verifying        : pfring-drivers-zc-dkms-7.9.0-3278.noarch                                                                     6/6
Installed products updated.

Installed:
  e1000e-zc-3.4.0.2.3278-dkms.noarch        i40e-zc-2.4.6.3278-dkms.noarch           igb-zc-5.3.5.18.3278-dkms.noarch
  ixgbe-zc-5.5.3.3278-dkms.noarch           ixgbevf-zc-4.5.1.3278-dkms.noarch        pfring-drivers-zc-dkms-7.9.0-3278.noarch

Complete!


Including all the make.log files for all the drivers this time.
[make-igb-zc.log](https://github.com/ntop/PF_RING/files/5575349/make-igb-zc.log)
[make-ixgbevf-zc.log](https://github.com/ntop/PF_RING/files/5575350/make-ixgbevf-zc.log)
[make-e1000e-zc.log](https://github.com/ntop/PF_RING/files/5575352/make-e1000e-zc.log)
[make-i40e-zc.log](https://github.com/ntop/PF_RING/files/5575354/make-i40e-zc.log)
[make-ixgbe-zc.log](https://github.com/ntop/PF_RING/files/5575357/make-ixgbe-zc.log)

**Comment by cardigliano** [comment]
@Arislen I pushed more patches to support RH8, please check it

**Comment by Arislen** [comment]
No go, all zc drivers failed.

Versions tested:

i40e-zc-2.4.6.3289-dkms.noarch
ixgbevf-zc-4.5.1.3289-dkms.noarch
ixgbe-zc-5.5.3.3289-dkms.noarch
pfring-drivers-zc-dkms-7.9.0-3289.noarch
igb-zc-5.3.5.18.3289-dkms.noarch
pfring-7.9.0-3289.x86_64
pfring-dkms-7.9.0-3289.noarch

dnf output:

Loading new ixgbevf-zc-4.5.1.3289 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbevf-zc/4.5.1.3289/build/make.log for more information.
warning: %post(ixgbevf-zc-4.5.1.3289-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbevf-zc
  Installing       : ixgbe-zc-5.5.3.3289-dkms.noarch                                                                              2/6
  Running scriptlet: ixgbe-zc-5.5.3.3289-dkms.noarch                                                                              2/6
Loading new ixgbe-zc-5.5.3.3289 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.3289/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.3289-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbe-zc
  Installing       : igb-zc-5.3.5.18.3289-dkms.noarch                                                                             3/6
  Running scriptlet: igb-zc-5.3.5.18.3289-dkms.noarch                                                                             3/6
Loading new igb-zc-5.3.5.18.3289 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/igb-zc/5.3.5.18.3289/build/make.log for more information.
warning: %post(igb-zc-5.3.5.18.3289-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package igb-zc
  Installing       : i40e-zc-2.4.6.3289-dkms.noarch                                                                               4/6
  Running scriptlet: i40e-zc-2.4.6.3289-dkms.noarch                                                                               4/6
Loading new i40e-zc-2.4.6.3289 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/i40e-zc/2.4.6.3289/build/make.log for more information.
warning: %post(i40e-zc-2.4.6.3289-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package i40e-zc
  Installing       : e1000e-zc-3.4.0.2.3289-dkms.noarch                                                                           5/6
  Running scriptlet: e1000e-zc-3.4.0.2.3289-dkms.noarch                                                                           5/6
Loading new e1000e-zc-3.4.0.2.3289 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.4.0.2.3289/build/make.log for more information.
warning: %post(e1000e-zc-3.4.0.2.3289-dkms.noarch) scriptlet failed, exit status 10


make.log files:

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/5662451/e1000e-zc-make.log)
[i40e-zc-make.log](https://github.com/ntop/PF_RING/files/5662452/i40e-zc-make.log)
[igb-zc-make.log](https://github.com/ntop/PF_RING/files/5662453/igb-zc-make.log)
[ixgbe-zc-make.log](https://github.com/ntop/PF_RING/files/5662454/ixgbe-zc-make.log)
[ixgbevf-zc-make.log](https://github.com/ntop/PF_RING/files/5662455/ixgbevf-zc-make.log)

**Comment by cardigliano** [comment]
@Arislen unfortunately I do not have access to that kernel, which has not been released for CentOS yet, to test the changes.

**Comment by cardigliano** [comment]
@Arislen I pushed a new update that should fix the compilation errors you reported, please check it

**Comment by Arislen** [comment]
Some ZC drivers now work, others still have issues:

Versions tested:

ixgbevf-zc-4.5.1.3299-dkms.noarch  (worked)
igb-zc-5.3.5.18.3299-dkms.noarch   (failed)
i40e-zc-2.4.6.3299-dkms.noarch      (worked)
e1000e-zc-3.4.0.2.3299-dkms.noarch  (failed)
ixgbe-zc-5.5.3.3299-dkms.noarch   (failed)

pfring-7.9.0-3299.x86_64
pfring-drivers-zc-dkms-7.9.0-3299.noarch
pfring-dkms-7.9.0-3299.noarch

dnf output:

Loading new ixgbevf-zc-4.5.1.3299 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Done.

ixgbevf_zc.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.18.0-240.1.1.el8_3.x86_64/extra/
Adding any weak-modules

depmod.....

DKMS: install completed.

  Installing       : ixgbe-zc-5.5.3.3299-dkms.noarch                                                                              2/6
  Running scriptlet: ixgbe-zc-5.5.3.3299-dkms.noarch                                                                              2/6
Loading new ixgbe-zc-5.5.3.3299 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.3299/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.3299-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbe-zc
  Installing       : igb-zc-5.3.5.18.3299-dkms.noarch                                                                             3/6
  Running scriptlet: igb-zc-5.3.5.18.3299-dkms.noarch                                                                             3/6
Loading new igb-zc-5.3.5.18.3299 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Done.

igb_zc.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.18.0-240.1.1.el8_3.x86_64/extra/
Adding any weak-modules

depmod.....

DKMS: install completed.

  Installing       : i40e-zc-2.4.6.3299-dkms.noarch                                                                               4/6
  Running scriptlet: i40e-zc-2.4.6.3299-dkms.noarch                                                                               4/6
Loading new i40e-zc-2.4.6.3299 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/i40e-zc/2.4.6.3299/build/make.log for more information.
warning: %post(i40e-zc-2.4.6.3299-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package i40e-zc
  Installing       : e1000e-zc-3.4.0.2.3299-dkms.noarch                                                                           5/6
  Running scriptlet: e1000e-zc-3.4.0.2.3299-dkms.noarch                                                                           5/6
Loading new e1000e-zc-3.4.0.2.3299 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.4.0.2.3299/build/make.log for more information.
warning: %post(e1000e-zc-3.4.0.2.3299-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc

make.log files:

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/5689591/e1000e-zc-make.log)
[i40e-zc-make.log](https://github.com/ntop/PF_RING/files/5689593/i40e-zc-make.log)
[ixgbe-zc-make.log](https://github.com/ntop/PF_RING/files/5689594/ixgbe-zc-make.log)

**Comment by cardigliano** [comment]
i40e and ixgbe have been updated on git, new build soon

**Comment by Arislen** [comment]
All fixed except:

e1000e-zc-3.4.0.2.3304-dkms.noarch


dnf output:

  Installing       : e1000e-zc-3.4.0.2.3304-dkms.noarch                                                                           5/6
  Running scriptlet: e1000e-zc-3.4.0.2.3304-dkms.noarch                                                                           5/6
Loading new e1000e-zc-3.4.0.2.3304 DKMS files...
Building for 4.18.0-240.8.1.el8_3.x86_64
Building initial module for 4.18.0-240.8.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.8.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.4.0.2.3304/build/make.log for more information.
warning: %post(e1000e-zc-3.4.0.2.3304-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc

make.log file:

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/5698772/e1000e-zc-make.log)

**Comment by cardigliano** [comment]
New e1000e patch in https://github.com/ntop/PF_RING/commit/e489fc07a6e642814f94158c8929eb21a0d17982

**Comment by Arislen** [comment]
Still have errors. 

e1000e-zc-3.4.0.2.3307-dkms.noarch 

dnf output:

Installing       : e1000e-zc-3.4.0.2.3307-dkms.noarch                                                                           5/6
Running scriptlet: e1000e-zc-3.4.0.2.3307-dkms.noarch                                                                           5/6
Loading new e1000e-zc-3.4.0.2.3307 DKMS files...
Building for 4.18.0-240.8.1.el8_3.x86_64
Building initial module for 4.18.0-240.8.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.8.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.4.0.2.3307/build/make.log for more information.
warning: %post(e1000e-zc-3.4.0.2.3307-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc

make.log file:

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/5711586/e1000e-zc-make.log)

**Comment by cardigliano** [comment]
I patched latest e1000e driver from intel, please check latest dev build

**Comment by Arislen** [comment]
Still have errors.

e1000e-zc-3.8.7.3316-dkms.noarch

dnf output:

Installing       : e1000e-zc-3.8.7.3316-dkms.noarch                                                                             5/6
Running scriptlet: e1000e-zc-3.8.7.3316-dkms.noarch                                                                             5/6
Loading new e1000e-zc-3.8.7.3316 DKMS files...
Building for 4.18.0-240.8.1.el8_3.x86_64
Building initial module for 4.18.0-240.8.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.8.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.8.7.3316/build/make.log for more information.
warning: %post(e1000e-zc-3.8.7.3316-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc

make.log file:

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/5734895/e1000e-zc-make.log)
