### ISSUE TITLE
Kernel 4.9 Driver Incompatibility

### ISSUE THREAD

**Issue by Manouchehri** [ntop/PF_RING#212]
Most of PF_RING itself works fine with 4.9, but the drivers don't.

```bash
[dave@lake ~]$ cd ~/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src
[dave@lake src]$ make
make -C /lib/modules/4.9.27-1-lts/build SUBDIRS=/home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src modules
make[1]: Entering directory '/usr/lib/modules/4.9.27-1-lts/build'
  CC [M]  /home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.o
/home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:2650:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_set_vf_vlan = igb_ndo_set_vf_vlan,
                     ^~~~~~~~~~~~~~~~~~~
/home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:2650:21: note: (near initialization for ‘igb_netdev_ops.ndo_set_vf_vlan’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:294: /home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.o] Error 1
make[1]: *** [Makefile:1490: _module_/home/dave/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.9.27-1-lts/build'
make: *** [Makefile:295: default] Error 2
```

Previously mentioned in https://github.com/ntop/PF_RING/issues/193#issuecomment-293096923.

**Comment by cardigliano** [comment]
@Manouchehri we are working for supporting latest kernels (see for instance the new ixgbe driver https://github.com/ntop/PF_RING/tree/dev/drivers/intel/ixgbe under testing), however our priority is supporting LTS kernels. What distro/version are you using?

**Comment by Manouchehri** [comment]
@cardigliano I was testing with Arch Linux's LTS kernel. https://www.archlinux.org/packages/core/x86_64/linux-lts/

(Ended up switching to Ubuntu 16.04.2 LTS on this box, seems easier.)

**Comment by cardigliano** [comment]
Arch Linux is not in the list of our supported distributions, however we will do our best to support that kernel too. However since you moved to Ubuntu I am going to close this issue.
