### ISSUE TITLE
build fails on RHEL7.4

### ISSUE THREAD

**Issue by d3matt** [ntop/PF_RING#249]
Looks like there are multiple kabi changes affecting pfring... Here's a patch that at least gets it to build

```
diff -ruN PF_RING-6.4.1-ORIG/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c PF_RING-6.4.1/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c
--- PF_RING-6.4.1-ORIG/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c  2016-06-16 03:38:54.000000000 -0600
+++ PF_RING-6.4.1/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c       2017-08-24 16:33:16.941345839 -0600
@@ -2647,7 +2647,9 @@
        .ndo_vlan_rx_kill_vid   = igb_vlan_rx_kill_vid,
 #ifdef IFLA_VF_MAX
        .ndo_set_vf_mac         = igb_ndo_set_vf_mac,
+#if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
        .ndo_set_vf_vlan        = igb_ndo_set_vf_vlan,
+#endif
 #ifdef HAVE_NDO_SET_VF_MIN_MAX_TX_RATE
        .ndo_set_vf_rate        = igb_ndo_set_vf_bw,
 #else
diff -ruN PF_RING-6.4.1-ORIG/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h PF_RING-6.4.1/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h
--- PF_RING-6.4.1-ORIG/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h   2017-08-24 16:32:06.344177621 -0600
+++ PF_RING-6.4.1/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h        2017-08-24 16:33:10.518148573 -0600
@@ -4963,7 +4963,7 @@
 #undef HAVE_STRUCT_PAGE_PFMEMALLOC
 #endif /* 4.1.9 */
 
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,2,0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,2,0)) && !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
 #else
 #define HAVE_NDO_DFLT_BRIDGE_GETLINK_VLAN_SUPPORT
 #endif /* 4.2.0 */
@@ -5034,10 +5034,13 @@
 }
 
 #endif /* UBUNTU_VERSION(4,4,0,21) */
+
+#if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
 static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
 {
        * sum = csum_fold(csum_add(diff, ~csum_unfold(*sum)));
 }
+#endif
 
 #if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,2)))
 static inline void page_ref_inc(struct page *page)
```

**Comment by cardigliano** [comment]
@d3matt thank you for reporting, however please consider moving to latest stable (6.6)

**Comment by d3matt** [comment]
dev and 6.6.0-stable both fail in a similar way... My patch doesn't apply as it's out of date, but it should be close... Here's the error for a clean clone of the dev branch

    [root@cit1-vm-tsa src]# pwd
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src
    [root@cit1-vm-tsa src]# make 
    gcc: error: unrecognized command line option ‘-no-pie’
    make -C /lib/modules/3.10.0-693.el7.x86_64/build SUBDIRS=/root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src modules
    make[1]: Entering directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
    gcc: error: unrecognized command line option ‘-no-pie’
      CC [M]  /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.o
    In file included from /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb.h:55:0,
                     from /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:51:
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h:5037:20: error: redefinition of ‘csum_replace_by_diff’
     static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
                        ^
    In file included from include/linux/skbuff.h:30:0,
                     from include/linux/if_ether.h:23,
                     from include/uapi/linux/ethtool.h:18,
                     from include/linux/ethtool.h:17,
                     from include/linux/netdevice.h:43,
                     from /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:30:
    include/net/checksum.h:110:20: note: previous definition of ‘csum_replace_by_diff’ was here
     static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
                        ^
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:2628:2: error: too few arguments to function ‘ndo_dflt_bridge_getlink’
      return ndo_dflt_bridge_getlink(skb, pid, seq, dev, mode, 0, 0, nlflags);
      ^
    In file included from include/net/dst.h:13:0,
                     from include/net/sock.h:72,
                     from include/linux/tcp.h:23,
                     from /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:31:
    include/linux/rtnetlink.h:115:12: note: declared here
     extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
                ^
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c: At top level:
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:2655:2: error: unknown field ‘ndo_set_vf_vlan’ specified in initializer
      .ndo_set_vf_vlan = igb_ndo_set_vf_vlan,
      ^
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
    /root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c:2634:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    make[2]: *** [/root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.o] Error 1
    make[1]: *** [_module_/root/PF_RING/drivers/intel/igb/igb-5.3.3.5-zc/src] Error 2
    make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
    make: *** [default] Error 2
    [root@cit1-vm-tsa src]# uname -a
    Linux cit1-vm-tsa.pplab.jdsu.net 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
    [root@cit1-vm-tsa src]# cat /etc/redhat-release 
    Red Hat Enterprise Linux Server release 7.4 (Maipo)
    [root@cit1-vm-tsa src]# git show HEAD^C
    [root@cit1-vm-tsa src]# git log -1
    commit fc685eccdd709cd79696268174234fe5f0de21ae
    Author: Alfredo Cardigliano <cardigliano@ntop.org>
    Date:   Thu Aug 31 18:49:46 2017 +0200

        comments

**Comment by d3matt** [comment]
Here's a patch against dev that fixes the build on RHEL7.4

    diff --git a/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c b/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c
    index e708396..ab5b18a 100644
    --- a/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c
    +++ b/drivers/intel/igb/igb-5.3.3.5-zc/src/igb_main.c
    @@ -2652,7 +2652,9 @@ static const struct net_device_ops igb_netdev_ops = {
            .ndo_vlan_rx_kill_vid   = igb_vlan_rx_kill_vid,
     #ifdef IFLA_VF_MAX
            .ndo_set_vf_mac         = igb_ndo_set_vf_mac,
    +#if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
            .ndo_set_vf_vlan        = igb_ndo_set_vf_vlan,
    +#endif
     #ifdef HAVE_NDO_SET_VF_MIN_MAX_TX_RATE
            .ndo_set_vf_rate        = igb_ndo_set_vf_bw,
     #else
    diff --git a/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h b/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h
    index 26a8752..1f3f914 100644
    --- a/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h
    +++ b/drivers/intel/igb/igb-5.3.3.5-zc/src/kcompat.h
    @@ -4963,7 +4963,7 @@ static inline bool page_is_pfmemalloc(struct page __maybe_unused *page)
     #undef HAVE_STRUCT_PAGE_PFMEMALLOC
     #endif /* 4.1.9 */
     
    -#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,2,0))
    +#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,2,0)) && !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
     #else
     #define HAVE_NDO_DFLT_BRIDGE_GETLINK_VLAN_SUPPORT
     #endif /* 4.2.0 */
    @@ -5034,10 +5034,13 @@ static inline void napi_consume_skb(struct sk_buff *skb,
     }
     
     #endif /* UBUNTU_VERSION(4,4,0,21) */
    +
    +#if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,3)))
     static inline void csum_replace_by_diff(__sum16 *sum, __wsum diff)
     {
            * sum = csum_fold(csum_add(diff, ~csum_unfold(*sum)));
     }
    +#endif
     
     #if !(RHEL_RELEASE_CODE && (RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(7,2)))
     static inline void page_ref_inc(struct page *page)

**Comment by d3matt** [comment]
Updated diff (apparently Konsole doesn't want to copy/paste correctly) is at https://github.com/d3matt/PF_RING/commit/640dc90be2dd05b3df97ca6a28c28e754a9310c1

**Comment by lobotmcj** [comment]
@d3matt I had the same issue but it now works with the latest commit to the stable branch https://github.com/ntop/PF_RING/commit/ee54df37464a427db39dc278f7828d9e2a2d1e3f
