### ISSUE TITLE
i40e_zc fails dkms on centos 7 3.10.0-862.3.2.el7

### ISSUE THREAD

**Issue by novaksam** [ntop/PF_RING#347]
Installing the i40e-zc DKMS from the unstable branch (stable fails too)

```
Error! Bad return status for module build on kernel: 3.10.0-862.3.2.el7.x86_64 (x86_64)
Consult /var/lib/dkms/i40e-zc/2.4.6.1975/build/make.log for more information.
warning: %post(i40e-zc-2.4.6.1975-dkms.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package i40e-zc-2.4.6.1975-dkms.noarch
```

/var/lib/dkms/i40e-zc/2.4.6.1975/build/make.log

```
DKMS make.log for i40e-zc-2.4.6.1975 for kernel 3.10.0-862.3.2.el7.x86_64 (x86_64)
Thu May 31 08:16:26 CDT 2018
make -C /lib/modules/3.10.0-862.3.2.el7.x86_64/build M=/var/lib/dkms/i40e-zc/2.4.6.1975/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-862.3.2.el7.x86_64'
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_main.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/kcompat.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_ethtool.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_adminq.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_common.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_hmc.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_lan_hmc.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_nvm.o
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_main.c: In function ‘i40e_open’:
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_main.c:6424:2: warning: implicit declaration of function ‘vxlan_get_rx_port’ [-Wimplicit-function-declaration]
  vxlan_get_rx_port(netdev);
  ^
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_main.c:6430:3: warning: implicit declaration of function ‘geneve_get_rx_port’ [-Wimplicit-function-declaration]
   geneve_get_rx_port(netdev);
   ^
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_debugfs.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_diag.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_ptp.o
  CC [M]  /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_client.o
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_debugfs.c: In function ‘i40e_dbg_netdev_ops_write’:
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_debugfs.c:2382:27: error: ‘const struct net_device_ops’ has no member named ‘ndo_change_mtu’
    vsi->netdev->netdev_ops->ndo_change_mtu(vsi->netdev,
                           ^
make[2]: *** [/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_debugfs.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c: In function ‘i40e_clean_rx_ring’:
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:1450:10: warning: passing argument 5 of ‘dma_unmap_page_attrs’ makes pointer from integer without a cast [enabled by default]
          I40E_RX_DMA_ATTR);
          ^
In file included from include/linux/skbuff.h:35:0,
                 from include/linux/tcp.h:21,
                 from include/net/tcp.h:24,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e.h:27,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:25:
include/linux/dma-mapping.h:218:20: note: expected ‘struct dma_attrs *’ but argument is of type ‘int’
 static inline void dma_unmap_page_attrs(struct device *dev,
                    ^
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c: In function ‘i40e_alloc_mapped_page’:
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:1642:6: warning: passing argument 6 of ‘dma_map_page_attrs’ makes pointer from integer without a cast [enabled by default]
      I40E_RX_DMA_ATTR);
      ^
In file included from include/linux/skbuff.h:35:0,
                 from include/linux/tcp.h:21,
                 from include/net/tcp.h:24,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e.h:27,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:25:
include/linux/dma-mapping.h:201:26: note: expected ‘struct dma_attrs *’ but argument is of type ‘int’
 static inline dma_addr_t dma_map_page_attrs(struct device *dev,
                          ^
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c: In function ‘i40e_put_rx_buffer’:
/var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:2356:10: warning: passing argument 5 of ‘dma_unmap_page_attrs’ makes pointer from integer without a cast [enabled by default]
          DMA_FROM_DEVICE, I40E_RX_DMA_ATTR);
          ^
In file included from include/linux/skbuff.h:35:0,
                 from include/linux/tcp.h:21,
                 from include/net/tcp.h:24,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e.h:27,
                 from /var/lib/dkms/i40e-zc/2.4.6.1975/build/i40e_txrx.c:25:
include/linux/dma-mapping.h:218:20: note: expected ‘struct dma_attrs *’ but argument is of type ‘int’
 static inline void dma_unmap_page_attrs(struct device *dev,
                    ^
make[1]: *** [_module_/var/lib/dkms/i40e-zc/2.4.6.1975/build] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-862.3.2.el7.x86_64'
make: *** [all] Error 2
```

I also modified my kernel Makefile to remove -Werror=implicit-function-declaration, which was causing i40e_main.c to fail, but it's still failing on the debug file.

**Comment by novaksam** [comment]
the issue appears to be caused by these bits
i40e_debugfs.c:2382
```
                        vsi->netdev->netdev_ops->ndo_change_mtu(vsi->netdev,
                                                                mtu);
```

i40e_main.c:10650
```
#ifdef HAVE_RHEL7_EXTENDED_MIN_MAX_MTU
        .extended.ndo_change_mtu = i40e_change_mtu,
#else
        .ndo_change_mtu         = i40e_change_mtu,
#endif /* HAVE_RHEL7_EXTENDED_MIN_MAX_MTU */
```

**Comment by cardigliano** [comment]
@novaksam I pushed a few fixes for Centos 7.5, building new packages right now, please try updating in ~30 min. Thank you.

**Comment by novaksam** [comment]
Looks good to me, thanks!
