### ISSUE TITLE
Unable to compile in Ubuntu 18.04

### ISSUE THREAD

**Issue by kahou82** [ntop/PF_RING#581]
I clone the dev branch and 7.6.0-stable but I am not able to compile PF_RING in my ubuntu 18.04 VM:

`Linux kahou 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
kahou@kahou:~/PF_RING$ make
cd kernel; make
make[1]: Entering directory '/home/kahou/PF_RING/kernel'
#make -C /lib/modules/4.15.0-96-generic/build SUBDIRS=/home/kahou/PF_RING/kernel EXTRA_CFLAGS='-I/home/kahou/PF_RING/kernel -DGIT_REV="\"7.6.0-stable:4302ee4535c4d007a28dc11586294a48ff881aa8\"" -no-pie -fno-pie' modules
make -C /lib/modules/4.15.0-96-generic/build M=/home/kahou/PF_RING/kernel EXTRA_CFLAGS='-I/home/kahou/PF_RING/kernel -DGIT_REV="\"7.6.0-stable:4302ee4535c4d007a28dc11586294a48ff881aa8\"" -no-pie -fno-pie' modules
make[2]: Entering directory '/usr/src/linux-headers-4.15.0-96-generic'
  CC [M]  /home/kahou/PF_RING/kernel/pf_ring.o
In file included from ./include/linux/list.h:5:0,
                 from ./include/linux/module.h:9,
                 from /home/kahou/PF_RING/kernel/pf_ring.c:79:
./include/linux/types.h:17:9: error: unknown type name ‘__kernel_ino_t’
 typedef __kernel_ino_t  ino_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:18:9: error: unknown type name ‘__kernel_mode_t’
 typedef __kernel_mode_t  mode_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:21:9: error: unknown type name ‘__kernel_off_t’
 typedef __kernel_off_t  off_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:22:9: error: unknown type name ‘__kernel_pid_t’
 typedef __kernel_pid_t  pid_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:23:9: error: unknown type name ‘__kernel_daddr_t’
 typedef __kernel_daddr_t daddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:25:9: error: unknown type name ‘__kernel_suseconds_t’
 typedef __kernel_suseconds_t suseconds_t;
         ^~~~~~~~~~~~~~~~~~~~
./include/linux/types.h:26:9: error: unknown type name ‘__kernel_timer_t’
 typedef __kernel_timer_t timer_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:27:9: error: unknown type name ‘__kernel_clockid_t’
 typedef __kernel_clockid_t clockid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:32:9: error: unknown type name ‘__kernel_uid32_t’
 typedef __kernel_uid32_t uid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:33:9: error: unknown type name ‘__kernel_gid32_t’
 typedef __kernel_gid32_t gid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:34:9: error: unknown type name ‘__kernel_uid16_t’
 typedef __kernel_uid16_t        uid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:35:9: error: unknown type name ‘__kernel_gid16_t’
 typedef __kernel_gid16_t        gid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:41:9: error: unknown type name ‘__kernel_old_uid_t’
 typedef __kernel_old_uid_t old_uid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:42:9: error: unknown type name ‘__kernel_old_gid_t’
 typedef __kernel_old_gid_t old_gid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:46:9: error: unknown type name ‘__kernel_loff_t’
 typedef __kernel_loff_t  loff_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:55:9: error: unknown type name ‘__kernel_size_t’
 typedef __kernel_size_t  size_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:60:9: error: unknown type name ‘__kernel_ssize_t’
 typedef __kernel_ssize_t ssize_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:65:9: error: unknown type name ‘__kernel_ptrdiff_t’
 typedef __kernel_ptrdiff_t ptrdiff_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:70:9: error: unknown type name ‘__kernel_time_t’
 typedef __kernel_time_t  time_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:75:9: error: unknown type name ‘__kernel_clock_t’
 typedef __kernel_clock_t clock_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:80:9: error: unknown type name ‘__kernel_caddr_t’
 typedef __kernel_caddr_t caddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:199:2: error: unknown type name ‘__kernel_daddr_t’
  __kernel_daddr_t f_tfree;
  ^~~~~~~~~~~~~~~~
./include/linux/types.h:200:2: error: unknown type name ‘__kernel_ino_t’
  __kernel_ino_t  f_tinode;
  ^~~~~~~~~~~~~~
In file included from ./include/linux/list.h:9:0,
                 from ./include/linux/module.h:9,
                 from /home/kahou/PF_RING/kernel/pf_ring.c:79:
./include/linux/kernel.h:6:10: fatal error: stdarg.h: No such file or directory
 #include <stdarg.h>
          ^~~~~~~~~~
compilation terminated.
scripts/Makefile.build:337: recipe for target '/home/kahou/PF_RING/kernel/pf_ring.o' failed
make[3]: *** [/home/kahou/PF_RING/kernel/pf_ring.o] Error 1
Makefile:1577: recipe for target '_module_/home/kahou/PF_RING/kernel' failed
make[2]: *** [_module_/home/kahou/PF_RING/kernel] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-96-generic'
Makefile:64: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kahou/PF_RING/kernel'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```
I have already installed the prereq from the README.FIRST (`apt-get install build-essential bison flex linux-headers-$(uname -r) libnuma-dev libnl-genl-3-dev`) but still no luck. Any idea what I am missing?

**Comment by kahou82** [comment]
Nvm. The problem goes away after I ran make clean && make.
