### ISSUE TITLE
Error while compiling PF_RING

### ISSUE THREAD

**Issue by jppo** [ntop/PF_RING#314]
Hello,

PF_RING was compiling OK with dkms and the kernel module was created until the kernel 4.4.16, today I try to compile 4.15.0 and get an error while compiling, trace follows : 
make -C /lib/modules/4.15.0/build SUBDIRS=/DATA/usr_src/pfring-7.1.0 EXTRA_CFLAGS='-I/DATA/usr_src/pfring-7.1.0 -DGIT_REV="\"dev:fcc142db7e2d5586a2923cc20f6a2cc4d7ebded5\""' modules
make[1]: Entering directory '/DATA/usr_src/linux-4.15'
  CC [M]  /DATA/usr_src/pfring-7.1.0/pf_ring.o
/DATA/usr_src/pfring-7.1.0/pf_ring.c: In function ‘skb_ring_handler’:
/DATA/usr_src/pfring-7.1.0/pf_ring.c:3969:38: error: implicit declaration of function ‘ACCESS_ONCE’ [-Werror=implicit-function-declaration]
       u_short num_cluster_elements = ACCESS_ONCE(cluster_ptr->cluster.num_cluster_elements);
                                      ^~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:322: recipe for target '/DATA/usr_src/pfring-7.1.0/pf_ring.o' failed
make[2]: *** [/DATA/usr_src/pfring-7.1.0/pf_ring.o] Error 1
Makefile:1508: recipe for target '_module_/DATA/usr_src/pfring-7.1.0' failed
make[1]: *** [_module_/DATA/usr_src/pfring-7.1.0] Error 2
make[1]: Leaving directory '/DATA/usr_src/linux-4.15'
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2
-----------------------------------------------------------------------------------------------------
Looking kernel 4.14 includes in .../include/linux I can see definition and references to ACCESS_ONCE, while looking in the 4.15 tree i do not find any definition nor reference to ACCESS_ONCE.

Regards

JP P

**Comment by cardigliano** [comment]
@jppo what linux distribution/version are you using?
Please note we support LTS versions (ubuntu, centos), however please try with our dev code from github as we try to push patches for latest kernel.

**Comment by jppo** [comment]
Hello, 

Sorry to not say my system : 
Debian Stretch up to date 
Cpus : Core I3 et Corei5 (two systems) 
Ram : 16Gb 
Some disks (mix of SSD and hard disks). 

I will try to download from github and give a try on my test system (Corei3). 

Thank you. 

Regards 

JP P

**Comment by cardigliano** [comment]
@jppo did you have a chance to try latest dev code?
BTW, upgrading my stretch box I get kernel 4.9, how did you get 4.15?

**Comment by YongHoPark** [comment]
@jppo and @cardigliano 

I found that ACCESS_ONCE was removed on 2017-12-12 from [git of kernerl.org](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/include/linux/compiler.h?h=v4.15.4&id=b899a850431e2dd0943205a63a68573f3e312d0d).

I wonder if it's possible to use READ_ONCE instead of ACCESS_ONCE If the meaning of the using ACCESS_ONCE on the following code is to prevent the compiler from optimizing.  

from
```
    while(cluster_ptr != NULL) {
      struct pf_ring_socket *pfr;
      u_short num_cluster_elements = ACCESS_ONCE(cluster_ptr->cluster.num_cluster_elements);

      if(num_cluster_elements > 0) {
	u_short num_iterations;
```

to
```
    while(cluster_ptr != NULL) {
      struct pf_ring_socket *pfr;
      u_short num_cluster_elements = READ_ONCE(cluster_ptr->cluster.num_cluster_elements);

      if(num_cluster_elements > 0) {
	u_short num_iterations;
```
Thanks,
YongHoPark

**Comment by cardigliano** [comment]
Using READ_ONCE on kernel 4.15 now, please check latest dev code. Thank you.

**Comment by jppo** [comment]
Hello, 

I get the last version from GITHUB, and try to compile with kernel 4.15.4 but I get some errors : 
-------------------------------------------------------------------------------------------------------------------------------------------- 
CC [M] /DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c: In function ‘e1000_probe’: 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8680:2: error: implicit declaration of function ‘init_timer’ [-Werror=implicit-function-declaration] 
init_timer(&adapter->watchdog_timer); 
^~~~~~~~~~ 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8681:35: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types] 
adapter->watchdog_timer.function = e1000_watchdog; 
^ 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8682:25: error: ‘struct timer_list’ has no member named ‘data’ 
adapter->watchdog_timer.data = (unsigned long)adapter; 
^ 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8685:35: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types] 
adapter->phy_info_timer.function = e1000_update_phy_info; 
^ 
/DATA/usr_src/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8686:25: error: ‘struct timer_list’ has no member named ‘data’ 
adapter->phy_info_timer.data = (unsigned long)adapter; 
^ 
----------------------------------------------------------------------------------------------------------------- 

I enclose the full compile log. 

Regards 

JP Pozzi
