### ISSUE TITLE
Problem building ice-zc-1.9.11.8309-dkms.noarch on RHEL 8

### ISSUE THREAD

**Issue by mvi57** [ntop/PF_RING#873]
I'm having trouble getting ice-zc-1.9.11.8309-dkms.noarch to build on RHEL 8 running kernel 4.18.0-477.10.1.el8_8.x86_64 or 4.18.0-477.13.1.el8_8.x86_64. The dkms compile is failing with errors like this:

  CC [M]  /var/lib/dkms/ice-zc/1.9.11.8309/build/ice_arfs.o
/var/lib/dkms/ice-zc/1.9.11.8309/build/ice_main.c: In function ‘ice_napi_add’:
/var/lib/dkms/ice-zc/1.9.11.8309/build/ice_main.c:4406:42: error: macro "netif_napi_add" passed 4 arguments, but takes just 3
           ice_napi_poll, NAPI_POLL_WEIGHT);
                                          ^
  CC [M]  /var/lib/dkms/ice-zc/1.9.11.8309/build/ice_debugfs.o
/var/lib/dkms/ice-zc/1.9.11.8309/build/ice_main.c:4405:3: error: ‘netif_napi_add’ undeclared (first use in this function); did you mean ‘netif_napi_del’?
   netif_napi_add(vsi->netdev, &vsi->q_vectors[v_idx]->napi,
   ^~~~~~~~~~~~~~
   netif_napi_del

**Comment by cardigliano** [comment]
It seems you are compiling from pf_ring stable, we recently pushed compilation fixes for the latest kernels on the dev branch, any chance you can check that branch?

**Comment by mvi57** [comment]
I tried the rpms that were on the nightly area of packages.ntop.org (which appear to have been updated today) but got the same errors.

**Comment by mvi57** [comment]
It looks like somewhere between kernel 4.18.0-425.19.2.el8_7.x86_64 and kernel 4.18.0-477.10.1.el8_8.x86_64 the definition of "netif_napi_add" changed.  They also added "netif_napi_add_weight".  I changed the three occurrences of netif_napi_add to netif_napi_add_weight in the ice-zc sources and the module compiled.  I didn't test it since I don't know what changing that would do.

**Comment by cardigliano** [comment]
RH 8.8 compilation fixed in 0190772051b61a4e852ced36417ca6ad86089bab (new build will be available soon)

**Comment by mvi57** [comment]
ice-zc v1.9.11.8377-dkms compiles and runs on CentOS 8 now.  Thank you!
