### ISSUE TITLE
Fails to Compile on 5.9

### ISSUE THREAD

**Issue by sempervictus** [ntop/PF_RING#678]
Looks like `timeval` isn't a thing anymore, and the call convention for `proc_create_data` has changed as well:
```
net/pf_ring/pf_ring.c: In function ‘set_skb_time’:
net/pf_ring/pf_ring.c:2662:13: error: implicit declaration of function ‘ktime_to_timeval’; did you mean ‘ktime_get_real’? [-Werror=implicit-function-declaration]
 2662 |   hdr->ts = ktime_to_timeval(skb->tstamp);
...
net/pf_ring/pf_ring.c:4324:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 4324 |      &ring_proc_virtual_filtering_fops /* read */,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      |
      |      const struct file_operations *
In file included from net/pf_ring/pf_ring.c:102:
./include/linux/proc_fs.h:109:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
  109 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
net/pf_ring/pf_ring.c: In function ‘setSocketStats’:
net/pf_ring/pf_ring.c:6249:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 6249 |      &ring_proc_stats_fops, pfr)) == NULL) {
      |      ^~~~~~~~~~~~~~~~~~~~~
      |      |
      |      const struct file_operations *
In file included from net/pf_ring/pf_ring.c:102:
./include/linux/proc_fs.h:109:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
  109 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
net/pf_ring/pf_ring.c: In function ‘ring_setsockopt’:
net/pf_ring/pf_ring.c:7054:48: error: incompatible type for argument 4 of ‘sock_setsockopt’
 7054 |   return(sock_setsockopt(sock, level, optname, optval, optlen));
      |                                                ^~~~~~
      |                                                |
      |                                                char *
In file included from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from net/pf_ring/pf_ring.c:94:
./include/net/sock.h:1677:17: note: expected ‘sockptr_t’ but argument is of type ‘char *’
 1677 |       sockptr_t optval, unsigned int optlen);
      |       ~~~~~~~~~~^~~~~~
net/pf_ring/pf_ring.c: At top level:
net/pf_ring/pf_ring.c:7705:17: error: initialization of ‘int (*)(struct socket *, int,  int,  sockptr_t,  unsigned int)’ from incompatible pointer type ‘int (*)(struct socket *, int,  int,  char *, unsigned int)’ [-Werror=incompatible-pointer-types]
 7705 |   .setsockopt = ring_setsockopt,
      |                 ^~~~~~~~~~~~~~~
net/pf_ring/pf_ring.c:7705:17: note: (near initialization for ‘ring_ops.setsockopt’)
net/pf_ring/pf_ring.c: In function ‘add_device_to_ring_list’:
net/pf_ring/pf_ring.c:7824:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 7824 |      &ring_proc_dev_fops /* read */,
      |      ^~~~~~~~~~~~~~~~~~~
      |      |
      |      const struct file_operations *
In file included from net/pf_ring/pf_ring.c:102:
./include/linux/proc_fs.h:109:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
  109 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
net/pf_ring/pf_ring.c: In function ‘ring_notifier’:
net/pf_ring/pf_ring.c:8072:9: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 8072 |         &ring_proc_dev_fops /* read */,
      |         ^~~~~~~~~~~~~~~~~~~
      |         |
      |         const struct file_operations *
In file included from net/pf_ring/pf_ring.c:102
```
Working on forward-porting some of the 5.4 branches we have to 5.9 in hope of a performance boost, looks like the API changes were "not minor" over the last 5 minor versions. :)
This is PF_RING 6.x, will try to pull v7 in-tree and see if that fares any better.

**Comment by cardigliano** [comment]
@sempervictus kernel 5.9 is not yet supported (we officially support LTS kernels only), we will support it asap

**Comment by dv0** [comment]
hello，the latest code compiled under kernel 5.10 still has similar problems.is there a definite plan to support kernel 5.10?

**Comment by cardigliano** [comment]
@dv0 we officially support LTS kernels only. What "similar problems" are you experiencing?

**Comment by dv0** [comment]
@cardigliano 

>   CC [M]  /home/dv/PF_RING-dev/kernel/pf_ring.o
/home/dv/PF_RING-dev/kernel/pf_ring.c: In function ‘ring_setsockopt’:
/home/dv/PF_RING-dev/kernel/pf_ring.c:7286:21: error: incompatible type for argument 1 of ‘copy_to_user’
     if(copy_to_user(optval, &mapping, optlen)) /* returning device_model*/
                     ^~~~~~
In file included from ./include/linux/sched/task.h:11:0,
                 from ./include/linux/sched/signal.h:9,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:33,
                 from ./arch/arm64/include/asm/elf.h:141,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:18,
                 from /home/dv/PF_RING-dev/kernel/pf_ring.c:79:
./include/linux/uaccess.h:197:1: note: expected ‘void *’ but argument is of type ‘sockptr_t {aka struct <anonymous>}’
 copy_to_user(void __user *to, const void *from, unsigned long n)
 ^~~~~~~~~~~~
/home/dv/PF_RING-dev/kernel/pf_ring.c:7417:23: error: incompatible type for argument 1 of ‘copy_to_user’
       if(copy_to_user(optval, &ccri, sizeof(ccri))) {
                       ^~~~~~
In file included from ./include/linux/sched/task.h:11:0,
                 from ./include/linux/sched/signal.h:9,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:33,
                 from ./arch/arm64/include/asm/elf.h:141,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:18,
                 from /home/dv/PF_RING-dev/kernel/pf_ring.c:79:
./include/linux/uaccess.h:197:1: note: expected ‘void *’ but argument is of type ‘sockptr_t {aka struct <anonymous>}’
 copy_to_user(void __user *to, const void *from, unsigned long n)
 ^~~~~~~~~~~~
/home/dv/PF_RING-dev/kernel/pf_ring.c: At top level:

**Comment by dv0** [comment]
it looks like a problem caused by the parameter "optval" type change in the kernel 5.10.

**Comment by lipnitsk** [comment]
@cardigliano:
> @dv0 we officially support LTS kernels only.

5.10 is LTS (https://www.kernel.org/category/releases.html). Does d90bf9c4465ca47540ad0fa5984aa211a853dbce fix it? Are you planning on releasing 7.8.1 with that fix?

here is my trace:
```
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c: In function 'ring_setsockopt':
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:7554:48: error: incompatible type for argument 4 of 'sock_setsockopt'
   return(sock_setsockopt(sock, level, optname, optval, optlen));
                                                ^~~~~~
In file included from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from /home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:91:
./include/net/sock.h:1675:17: note: expected 'sockptr_t' {aka 'struct <anonymous>'} but argument is of type 'char *'
       sockptr_t optval, unsigned int optlen);
       ~~~~~~~~~~^~~~~~
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c: At top level:
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:8179:17: error: initialization of 'int (*)(struct socket *, int,  int,  sockptr_t,  unsigned int)' {aka 'int (*)(struct socket *, int,  int,  struct <anonymous>,  unsigned int)'} from incompatible pointer type 'int (*)(struct socket *, int,  int,  char *, unsigned int)' [-Werror=incompatible-pointer-types]
   .setsockopt = ring_setsockopt,
                 ^~~~~~~~~~~~~~~
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:8179:17: note: (near initialization for 'ring_ops.setsockopt')
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c: In function 'hash_pkt_cluster':
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:3910:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if(l3_proto == IPPROTO_TCP)
       ^
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:3917:3: note: here
   case cluster_per_flow_2_tuple:
   ^~~~
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c: In function 'ring_setsockopt':
/home/lipnitsk/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/PF_RING-7.8.0/kernel/pf_ring.c:7555:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: some warnings being treated as errors
```

**Comment by cardigliano** [comment]
@lipnitsk let me be more precise, we support kernels used by Ubuntu Server LTS, CentOS, Debian. 
Is the latest pf_ring dev code working for you?

**Comment by lipnitsk** [comment]
I think `copy_to_user` within `ring_setsockopt` is still problematic with the optval type change. I'll see if I can make a PR to fix this.

**Comment by cardigliano** [comment]
PR accepted, thank you!

**Comment by lipnitsk** [comment]
@cardigliano thanks for merging the changes promptly! Are you planing a 7.8.1 release off the stable branch soon?

**Comment by cardigliano** [comment]
You're welcome, there is no plan to release a new stable yet
