### ISSUE TITLE
Compilation issues on Ubuntu 20.04.3 LTS 5.11.0-38-generic

### ISSUE THREAD

**Issue by cardigliano** [ntop/PF_RING#770]
ixgbe and i40e ZC drivers do not compile on latest Ubuntu 20.04.3 LTS kernel5.11.0-38-generic

/var/lib/dkms/ixgbe-zc/5.5.3.7085/build/ixgbe_main.c: In function ‘ixgbe_setup_rx_resources’: 
/var/lib/dkms/ixgbe-zc/5.5.3.7085/build/ixgbe_main.c:8124:6: error: too few arguments to function ‘xdp_rxq_info_reg’

**Comment by cardigliano** [comment]
Fixed in b553fd6389f5ed8b850122470b4c555f6697199d
