### ISSUE TITLE
Errors were encountered while processing: pfring-dkms | Ubuntu Mate 19.04 

### ISSUE THREAD

**Issue by TheJags** [ntop/PF_RING#472]
While trying to install Ntopng in Ubuntu Mate 19.04, I was getting quite a few errors but finally I'm stuck while manually trying to install pfring-dkms_7.5.0_all.deb ( as per this post: https://github.com/ntop/PF_RING/issues/388#issuecomment-415828668 )

$ wget http://packages.ntop.org/apt/18.04/all/pfring-dkms_7.5.0_all.deb

$ sudo dpkg -i pfring-dkms_7.5.0_all.deb
Selecting previously unselected package pfring-dkms.
(Reading database ... 200576 files and directories currently installed.)
Preparing to unpack pfring-dkms_7.5.0_all.deb ...
Unpacking pfring-dkms (7.5.0) ...
Setting up pfring-dkms (7.5.0) ...
Loading new pfring-7.5.0 DKMS files...
Building for 5.0.0-13-generic
Building for architecture x86_64
Building initial module for 5.0.0-13-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/pfring-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.0.0-13-generic (x86_64)
Consult /var/lib/dkms/pfring/7.5.0/build/make.log for more information.
dpkg: error processing package pfring-dkms (--install):
 installed pfring-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 pfring-dkms

/var/lib/dkms/pfring/7.5.0/build/make.log

DKMS make.log for pfring-7.5.0 for kernel 5.0.0-13-generic (x86_64)
Sat Apr 20 07:42:53 IST 2019
make -C /lib/modules/5.0.0-13-generic/build SUBDIRS=/var/lib/dkms/pfring/7.5.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/7.5.0/build -DGIT_REV="\"dev:95dedf7a68790f0aa2cfb7ad91479840fc65a898\"" -no-pie -fno-pie' modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/linux-headers-5.0.0-13-generic'
Makefile:203: ================= WARNING ================
Makefile:204: 'SUBDIRS' will be removed after Linux 5.3
Makefile:205: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:206: ==========================================
  CC [M]  /var/lib/dkms/pfring/7.5.0/build/pf_ring.o
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c: In function ‘set_netdev_promisc’:
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c:4943:5: error: too few arguments to function ‘dev_change_flags’
     dev_change_flags(netdev, if_flags);
     ^~~~~~~~~~~~~~~~
In file included from ./include/linux/rtnetlink.h:7,
                 from /var/lib/dkms/pfring/7.5.0/build/pf_ring.c:84:
./include/linux/netdevice.h:3631:5: note: declared here
 int dev_change_flags(struct net_device *dev, unsigned int flags,
     ^~~~~~~~~~~~~~~~
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c: In function ‘unset_netdev_promisc’:
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c:4961:5: error: too few arguments to function ‘dev_change_flags’
     dev_change_flags(netdev, if_flags);
     ^~~~~~~~~~~~~~~~
In file included from ./include/linux/rtnetlink.h:7,
                 from /var/lib/dkms/pfring/7.5.0/build/pf_ring.c:84:
./include/linux/netdevice.h:3631:5: note: declared here
 int dev_change_flags(struct net_device *dev, unsigned int flags,
     ^~~~~~~~~~~~~~~~
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c: In function ‘ring_notifier’:
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c:8099:7: error: duplicate case value
       case NETDEV_PRE_UP:           what = "NETDEV_PRE_UP"; break;
       ^~~~
/var/lib/dkms/pfring/7.5.0/build/pf_ring.c:8098:7: note: previously used here
       case NETDEV_BONDING_FAILOVER: what = "NETDEV_BONDING_FAILOVER"; break;
       ^~~~
make[2]: *** [scripts/Makefile.build:293: /var/lib/dkms/pfring/7.5.0/build/pf_ring.o] Error 1
make[1]: *** [Makefile:1584: _module_/var/lib/dkms/pfring/7.5.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-13-generic'
make: *** [Makefile:64: all] Error 2

**Comment by cardigliano** [comment]
@TheJags thank you for reporting, kernel 5.x is not yet supported, we officially support LTS kernels, we will do our best to support 5.x asap! Thank you.

**Comment by TheJags** [comment]
@cardigliano thanks for the reply. Last question, how to find out that kernel 5.x support has been added.

**Comment by cardigliano** [comment]
I will update this ticket, and it will be added to the changelog on the next release

**Comment by cardigliano** [comment]
@TheJags I pushed compilation fix for kernel 5.x, please give it a try if you get a chance (please note this is untested). Thank you.

**Comment by TheJags** [comment]
@cardigliano thanks alot. Now it got installed just fine. I was even able to set basic configuration too. Using Ntop first time ever and trying to analyze traffic.

Would this:
`https://www.ntop.org/guides/ntopng/`
be the best place to start learning about analyzing traffic or would you recommend any other guides?

Thanks.

**Comment by cardigliano** [comment]
@TheJags glad to see it is working, thank you for the update. That guide is definitely a good starting point for analysing your traffic.
