### ISSUE TITLE
PFring install fails under Oracle Linux 7.3 v4.1.12 UEK kernel

### ISSUE THREAD

**Issue by ssa5** [ntop/PF_RING#246]
This for Oracle Linux 7.3, kernel 4.1.12-94.5.7.el7uek.x86_64. This problem appears across multiple servers, as well as 2 fresh installs done yesterday. 7 VMs has ntopng and nprobe installed and working, recent yum update broke the install. 

From /var/log/messages
```
Aug  1 08:23:31 AN1 systemd: Starting LSB: Start/stop pf_ring...
Aug  1 08:23:31 AN1 pf_ring: Starting PF_RING module: modprobe: FATAL: Module pf_ring not found.
Aug  1 08:23:31 AN1 pf_ring: Uninstalling old pfring version
Aug  1 08:23:32 AN1 pf_ring: Error! The module pfring 6.6.0 is not currently installed.
Aug  1 08:23:32 AN1 pf_ring: This module is not currently ACTIVE for kernel 4.1.12-94.5.7.el7uek.x86_64 (x86_64).
Aug  1 08:23:32 AN1 pf_ring: Error! There is no instance of pfring 6.6.0
Aug  1 08:23:32 AN1 pf_ring: for kernel 4.1.12-94.5.7.el7uek.x86_64 (x86_64) located in the DKMS tree.
Aug  1 08:23:32 AN1 pf_ring: Compiling new pfring driver
Aug  1 08:23:34 AN1 pf_ring: Error! Bad return status for module build on kernel: 4.1.12-94.5.7.el7uek.x86_64 (x86_64)
Aug  1 08:23:34 AN1 pf_ring: Consult /var/lib/dkms/pfring/6.6.0/build/make.log for more information.
Aug  1 08:23:34 AN1 pf_ring: Installing new pfring driver
Aug  1 08:23:37 AN1 pf_ring: Error! Bad return status for module build on kernel: 4.1.12-94.5.7.el7uek.x86_64 (x86_64)
Aug  1 08:23:37 AN1 pf_ring: Consult /var/lib/dkms/pfring/6.6.0/build/make.log for more information.
Aug  1 08:23:37 AN1 pf_ring: modprobe: FATAL: Module pf_ring not found.
Aug  1 08:23:37 AN1 pf_ring: Unable to load PF_RING. Exiting[FAILED]
Aug  1 08:23:37 AN1 systemd: pf_ring.service: control process exited, code=exited status=99
Aug  1 08:23:37 AN1 systemd: Failed to start LSB: Start/stop pf_ring.
Aug  1 08:23:37 AN1 systemd: Dependency failed for Start/stop ntopng program.
Aug  1 08:23:37 AN1 systemd: Job ntopng.service/start failed with result 'dependency'.
Aug  1 08:23:37 AN1 systemd: Unit pf_ring.service entered failed state.
Aug  1 08:23:37 AN1 systemd: pf_ring.service failed.
```

From /var/lib/dkms/pfring/6.6.0/build/make.log
```
DKMS make.log for pfring-6.6.0 for kernel 4.1.12-94.5.7.el7uek.x86_64 (x86_64)
Tue Aug  1 08:23:36 CDT 2017
make -C /lib/modules/4.1.12-94.5.7.el7uek.x86_64/build SUBDIRS=/var/lib/dkms/pfring/6.6.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/6.6.0/build -DGIT_REV="\"6.6.0-stable:6a0984abff7a09f81d70b26cc06f3e0c78e544a9\""' modules
make[1]: Entering directory `/usr/src/kernels/4.1.12-94.5.7.el7uek.x86_64'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  CC [M]  /var/lib/dkms/pfring/6.6.0/build/pf_ring.o
/var/lib/dkms/pfring/6.6.0/build/pf_ring.c: In function â€˜ring_createâ€™:
/var/lib/dkms/pfring/6.6.0/build/pf_ring.c:4179:3: error: too few arguments to function â€˜sk_allocâ€™
   sk = sk_alloc(net, PF_INET, GFP_KERNEL, &ring_proto);
   ^
In file included from include/linux/tcp.h:22:0,
                 from include/linux/ipv6.h:69,
                 from /var/lib/dkms/pfring/6.6.0/build/pf_ring.c:94:
include/net/sock.h:1527:14: note: declared here
 struct sock *sk_alloc(struct net *net, int family, gfp_t priority,
              ^
make[2]: *** [/var/lib/dkms/pfring/6.6.0/build/pf_ring.o] Error 1
make[1]: *** [_module_/var/lib/dkms/pfring/6.6.0/build] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.1.12-94.5.7.el7uek.x86_64'
make: *** [all] Error 2
```

I have a CentOS7 that does not seem to have this issue, however it has kernel 3.10. This issue just appeared in the past couple of days, recent updates on servers last week did not introduce this issue. Also, I should clarify. Currently install is:
pfring-6.6.0-1353
ntopng-3.0.170719-2905
Updated available:
pfring-6.6.0-1372
ntopng-3.0.170726-2906

**Comment by cfrancis2b** [comment]
I found the same problem, to be able to solve you should uninstall pfring that uninstalls ntopng, reboot the computers and install.
The good thing is that the configuration data is not cleared.

At best you do not have to restart the pfring just reinstall.

**Comment by ssa5** [comment]
I have completely removed all trace of ntopng and pfring before attempting re-install. Done through both package manager as well as downloaded source with same issue. It seems to be completed centered around v4 kernel.

**Comment by cardigliano** [comment]
@ssa5 said that we do not support Oracle Linux, any chance you can provide access to one of those VM?

**Comment by ssa5** [comment]
Any fresh install of Oracle (now at 7.4) will replicate this. Upon install there are 2 kernel options, 3.10 or 4.1 UEK. v3.10 works, v4 does not;

<pre>
[root@oracle7 kernel]# uname -r
4.1.12-103.9.2.el7uek.x86_64
[root@oracle7 kernel]# make
make -C /lib/modules/4.1.12-103.9.2.el7uek.x86_64/build SUBDIRS=/root/PF_RING/kernel EXTRA_CFLAGS='-I/root/PF_RING/kernel -DGIT_REV="\"dev:be58bd38288455b9b359141fbc8265c122a16500\""' modules
make[1]: Entering directory `/usr/src/kernels/4.1.12-103.9.2.el7uek.x86_64'
  CC [M]  /root/PF_RING/kernel/pf_ring.o
/root/PF_RING/kernel/pf_ring.c: In function ‘ring_create’:
/root/PF_RING/kernel/pf_ring.c:4084:3: error: too few arguments to function ‘sk_alloc’
   sk = sk_alloc(net, PF_INET, GFP_KERNEL, &ring_proto);
   ^
In file included from include/linux/tcp.h:22:0,
                 from include/linux/ipv6.h:69,
                 from /root/PF_RING/kernel/pf_ring.c:90:
include/net/sock.h:1527:14: note: declared here
 struct sock *sk_alloc(struct net *net, int family, gfp_t priority,
              ^
make[2]: *** [/root/PF_RING/kernel/pf_ring.o] Error 1
make[1]: *** [_module_/root/PF_RING/kernel] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.1.12-103.9.2.el7uek.x86_64'
make: *** [all] Error 2
[root@oracle7 kernel]#
</pre>
whereas I reboot, this time selecting 3.10 as the kernel to load and I get;
<pre>
[root@oracle7 kernel]# uname -r
3.10.0-693.5.2.el7.x86_64
[root@oracle7 kernel]# make
make -C /lib/modules/3.10.0-693.5.2.el7.x86_64/build SUBDIRS=/root/PF_RING/kernel EXTRA_CFLAGS='-I/root/PF_RING/kernel -DGIT_REV="\"dev:be58bd38288455b9b359141fbc8265c122a16500\""' modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.5.2.el7.x86_64'
  CC [M]  /root/PF_RING/kernel/pf_ring.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/PF_RING/kernel/pf_ring.mod.o
  LD [M]  /root/PF_RING/kernel/pf_ring.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.5.2.el7.x86_64'
[root@oracle7 kernel]#
[root@oracle7 kernel]# systemctl start ntopng
[root@oracle7 kernel]# systemctl status ntopng
? ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-11-07 06:38:16 CST; 1s ago
  Process: 41135 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 41146 (ntopng)
   CGroup: /system.slice/ntopng.service
           +-41146 /usr/bin/ntopng /etc/ntopng/ntopng.conf
</pre>
I do not believe Centos provides any kernel other than 3.10 in its base repositories, and I can not say for certain for Red Hat though Oracle does seem to have literally taken RH and changed the logo and nothing else. I had seen post long before that v4 was not supported, but this was quite old. More recently I saw comment that ntop or pfring did support v4, which is why I came here hoping to resolve this.

**Comment by cardigliano** [comment]
Compilation issues with sk_alloc on kernel 4.x has been fixed some time ago, we also improved systemd support, please reopen if there are still issues on Oracle
