### ISSUE TITLE
Errors were encountered while processing:  pfring-dkms

### ISSUE THREAD

**Issue by seonghobae** [ntop/PF_RING#330]
```bash
root@login:~# apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-112 linux-headers-4.4.0-112-generic linux-image-4.4.0-112-generic linux-image-extra-4.4.0-112-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up pfring-dkms (7.1.0) ...
Removing old pfring-7.1.0 DKMS files...

------------------------------
Deleting module version: 7.1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new pfring-7.1.0 DKMS files...
First Installation: checking all kernels...
Building only for 4.16.0-041600rc2-lowlatency
Building for architecture x86_64
Building initial module for 4.16.0-041600rc2-lowlatency
ERROR (dkms apport): kernel package linux-headers-4.16.0-041600rc2-lowlatency is not supported
Error! Bad return status for module build on kernel: 4.16.0-041600rc2-lowlatency (x86_64)
Consult /var/lib/dkms/pfring/7.1.0/build/make.log for more information.
dpkg: error processing package pfring-dkms (--configure):
 subprocess installed post-installation script returned error exit status 10
Errors were encountered while processing:
 pfring-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@login:~# 
```

**Comment by seonghobae** [comment]
```bash
root@login:~# cat /var/lib/dkms/pfring/7.1.0/build/make.log 
DKMS make.log for pfring-7.1.0 for kernel 4.16.0-041600rc2-lowlatency (x86_64)
2018. 02. 22. (목) 12:20:00 JST
make -C /lib/modules/4.16.0-041600rc2-lowlatency/build SUBDIRS=/var/lib/dkms/pfring/7.1.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/7.1.0/build -DGIT_REV="\"dev:e35eba4cbaaeb2cf63eef98e80693ba6d0790132\""' modules
make[1]: Entering directory '/usr/src/linux-headers-4.16.0-041600rc2-lowlatency'
Makefile:970: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /var/lib/dkms/pfring/7.1.0/build/pf_ring.o
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c: In function ‘skb_ring_handler’:
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:3976:38: error: implicit declaration of function ‘ACCESS_ONCE’ [-Werror=implicit-function-declaration]
       u_short num_cluster_elements = ACCESS_ONCE(cluster_ptr->cluster.num_cluster_elements);
                                      ^
In file included from /var/lib/dkms/pfring/7.1.0/build/pf_ring.c:116:0:
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c: In function ‘ring_setsockopt’:
./include/generated/utsrelease.h:2:32: error: invalid suffix "rc2" on integer constant
 #define UTS_UBUNTU_RELEASE_ABI 041600rc2
                                ^
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:6370:57: note: in expansion of macro ‘UTS_UBUNTU_RELEASE_ABI’
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,2,0) && UTS_UBUNTU_RELEASE_ABI >= 28) || \
                                                         ^
./include/generated/utsrelease.h:2:32: error: invalid suffix "rc2" on integer constant
 #define UTS_UBUNTU_RELEASE_ABI 041600rc2
                                ^
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:6371:57: note: in expansion of macro ‘UTS_UBUNTU_RELEASE_ABI’
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,4,0) && UTS_UBUNTU_RELEASE_ABI >= 22))) || \
                                                         ^
./include/generated/utsrelease.h:2:32: error: invalid suffix "rc2" on integer constant
 #define UTS_UBUNTU_RELEASE_ABI 041600rc2
                                ^
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:6388:57: note: in expansion of macro ‘UTS_UBUNTU_RELEASE_ABI’
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,2,0) && UTS_UBUNTU_RELEASE_ABI >= 28) || \
                                                         ^
./include/generated/utsrelease.h:2:32: error: invalid suffix "rc2" on integer constant
 #define UTS_UBUNTU_RELEASE_ABI 041600rc2
                                ^
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:6389:57: note: in expansion of macro ‘UTS_UBUNTU_RELEASE_ABI’
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,4,0) && UTS_UBUNTU_RELEASE_ABI >= 22))) || \
                                                         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:322: recipe for target '/var/lib/dkms/pfring/7.1.0/build/pf_ring.o' failed
make[2]: *** [/var/lib/dkms/pfring/7.1.0/build/pf_ring.o] Error 1
Makefile:1555: recipe for target '_module_/var/lib/dkms/pfring/7.1.0/build' failed
make[1]: *** [_module_/var/lib/dkms/pfring/7.1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.16.0-041600rc2-lowlatency'
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by seonghobae** [comment]
```bash
root@login:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Comment by seonghobae** [comment]
```bash
root@login:~# dpkg --configure -D 777 gconf2
D000001: ensure_diversions: new, (re)loading
D000001: process queue pkg gconf2 queue.len 0 progress 1, try 1
dpkg: error processing package gconf2 (--configure):
 no package named 'gconf2' is installed, cannot configure
Errors were encountered while processing:
 gconf2
root@login:~# dpkg --configure -D 777 pfring-dkms
D000001: ensure_diversions: new, (re)loading
D000001: process queue pkg pfring-dkms:all queue.len 0 progress 1, try 1
D000040: checking dependencies of pfring-dkms:all (- <none>)
D000400:   checking group ...
D000400:     checking possibility  -> pfring
D000400:       checking non-provided pkg pfring:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> dkms
D000400:       checking non-provided pkg dkms:all
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000040: ok 2 msgs >><<
D000040:     checking Breaks
Setting up pfring-dkms (7.1.0) ...
D000002: fork/exec /var/lib/dpkg/info/pfring-dkms.postinst ( configure 7.1.0 )
Removing old pfring-7.1.0 DKMS files...

------------------------------
Deleting module version: 7.1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new pfring-7.1.0 DKMS files...
First Installation: checking all kernels...
Building only for 4.16.0-041600rc2-lowlatency
Building for architecture x86_64
Building initial module for 4.16.0-041600rc2-lowlatency
ERROR (dkms apport): kernel package linux-headers-4.16.0-041600rc2-lowlatency is not supported
Error! Bad return status for module build on kernel: 4.16.0-041600rc2-lowlatency (x86_64)
Consult /var/lib/dkms/pfring/7.1.0/build/make.log for more information.
dpkg: error processing package pfring-dkms (--configure):
 subprocess installed post-installation script returned error exit status 10
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 pfring-dkms

```

**Comment by cardigliano** [comment]
Hi @seonghobae, unstable kernels are not officially supported,
however we do our best to let you run pf_ring on any kernel, let us see if we can fix this.

**Comment by cardigliano** [comment]
@seonghobae in the last month we pushed patched to fix the compilation errors you reported, any news with this? Thank you.
