### ISSUE TITLE
error: incompatible type for argument 4 of ‘sock_setsockopt’

### ISSUE THREAD

**Issue by samyabdellatif** [ntop/PF_RING#669]
I'm getting this error for the second time when I do full upgrade > pacman -Syyu

`dkms install --no-depmod -m pfring -v 2855.2ba454aa -k 5.9.2-arch1-1
Error! Bad return status for module build on kernel: 5.9.2-arch1-1 (x86_64)
Consult /var/lib/dkms/pfring/2855.2ba454aa/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m pfring -v 2855.2ba454aa -k 5.9.2-arch1-1' returned 10 `

and this is the content of the make.log file

`DKMS make.log for pfring-2855.2ba454aa for kernel 5.9.2-arch1-1 (x86_64)
Sun Nov  1 02:20:15 PM +03 2020
make -C /lib/modules/5.9.2-arch1-1/build M=/var/lib/dkms/pfring/2855.2ba454aa/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/2855.2ba454aa/
build  -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/lib/modules/5.9.2-arch1-1/build'
  CC [M]  /var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.o
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c: In function ‘ring_setsockopt’:
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c:7554:48: error: incompatible type for argument 4 of ‘sock_setsockopt’
 7554 |   return(sock_setsockopt(sock, level, optname, optval, optlen));
      |                                                ^~~~~~
      |                                                |
      |                                                char *
In file included from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from /var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c:91:
./include/net/sock.h:1677:17: note: expected ‘sockptr_t’ but argument is of type ‘char *’
 1677 |       sockptr_t optval, unsigned int optlen);
      |       ~~~~~~~~~~^~~~~~
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c: At top level:
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c:8179:17: error: initialization of ‘int (*)(struct socket *, int,  int,  sockptr_t,  unsigned int)’ from incompatible pointer type ‘int (*)(struct socket *, int,  int,  char *, unsigned int)’ [-Werror=incompatible-pointer-types]
 8179 |   .setsockopt = ring_setsockopt,
      |                 ^~~~~~~~~~~~~~~
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c:8179:17: note: (near initialization for ‘ring_ops.setsockopt’)
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c: In function ‘ring_setsockopt’:
/var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.c:7555:1: warning: control reaches end of non-void function [-Wreturn-type]
 7555 | }
      | ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:283: /var/lib/dkms/pfring/2855.2ba454aa/build/pf_ring.o] Error 1
make[1]: *** [Makefile:1784: /var/lib/dkms/pfring/2855.2ba454aa/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.9.2-arch1-1/build'
make: *** [Makefile:67: all] Error 2 `

**Comment by cardigliano** [comment]
@samyabdellatif I pushed a blind fix for kernel 5.9 (please note this is not officially supported as we support Ubuntu LTS/Centos kernels). Please check latest github code.

**Comment by samyabdellatif** [comment]
> @samyabdellatif I pushed a blind fix for kernel 5.9 (please note this is not officially supported as we support Ubuntu LTS/Centos kernels). Please check latest github code.

Thanks a lot for your fast response, I'm still getting errors during the package building but I'm not sure if i'm doing it correctly.. so to avoid the support issues I will keep that on my ubuntu system. thank you
