### ISSUE TITLE
Kernel Module build fails with GCC 11.4.0 on kernel 6.2.0-26

### ISSUE THREAD

**Issue by jmartini89** [ntop/PF_RING#879]
Building PF_RING kernel module with GCC 11.4.0 fails.

The building enviornment is:
- Ubuntu 22.04
- Linux Kernel 6.2.0-26
- GCC 11.4.0

`make` output:
```
make -C /lib/modules/6.2.0-26-generic/build M=/home/jmartini/dev/third-party/PF_RING/kernel EXTRA_CFLAGS='-I/home/jmartini/dev/third-party/PF_RING/kernel -DGIT_REV="\"dev:a5313280c1f3eacdcf3bd7643b0feca073d4b4bc\"" -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[1]: Entering directory '/usr/src/linux-headers-6.2.0-26-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.o
/home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c: In function ‘ring_bind’:
/home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c:5572:21: error: invalid application of ‘sizeof’ to incomplete type ‘char[]’
 5572 |     char name[sizeof(sa->sa_data)+1];
      |                     ^
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/paravirt.h:17,
                 from ./arch/x86/include/asm/cpuid.h:62,
                 from ./arch/x86/include/asm/processor.h:19,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c:79:
/home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c:5577:37: error: invalid application of ‘sizeof’ to incomplete type ‘char[]’
 5577 |     memcpy(name, sa->sa_data, sizeof(sa->sa_data));
      |                                     ^
./include/linux/fortify-string.h:566:48: note: in definition of macro ‘__fortify_memcpy_chk’
  566 |         const size_t __fortify_size = (size_t)(size);                   \
      |                                                ^~~~
/home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c:5577:5: note: in expansion of macro ‘memcpy’
 5577 |     memcpy(name, sa->sa_data, sizeof(sa->sa_data));
      |     ^~~~~~
/home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.c:5572:10: warning: unused variable ‘name’ [-Wunused-variable]
 5572 |     char name[sizeof(sa->sa_data)+1];
      |          ^~~~
make[2]: *** [scripts/Makefile.build:260: /home/jmartini/dev/third-party/PF_RING/kernel/pf_ring.o] Error 1
make[1]: *** [Makefile:2026: /home/jmartini/dev/third-party/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.2.0-26-generic'
make: *** [Makefile:67: all] Error 2
```

**Comment by jmartini89** [comment]
Manually compiling and installing the kernel module works on kernel 5.19.0-50 using GCC 11.4.0

**Comment by cardigliano** [comment]
@jmartini89 we will check support for kernel 6.2 asap

**Comment by cardigliano** [comment]
I pushed a patch set to fix compilation on 6.2, please update and let me know.

**Comment by jmartini89** [comment]
@cardigliano [Update kernel APIs for ubuntu 22 kernel 6.2](https://github.com/ntop/PF_RING/commit/c0af55a921c1867db973d8885cadc425ea15b8a3) fixed the issue! Kernel module compilation and loading work as expected.

**Comment by cardigliano** [comment]
Thank you
