### ISSUE TITLE
Linux 6.3 compatibility

### ISSUE THREAD

**Issue by sempervictus** [ntop/PF_RING#884]
Working on a 6.3 build of our internal stack, i ran into the following errors:
```
net/pf_ring/pf_ring.c:2842:25: error: storage size of ‘state’ isn’t known
net/pf_ring/pf_ring.c:2860:17: error: implicit declaration of function ‘textsearch_find_continuous’ [-Werror=implicit-function-declaration]
net/pf_ring/pf_ring.c:3122:5: error: implicit declaration of function ‘textsearch_destroy’ [-Werror=implicit-function-declaration]
net/pf_ring/pf_ring.c:3333:28: error: implicit declaration of function ‘textsearch_prepare’ [-Werror=implicit-function-declaration]
net/pf_ring/pf_ring.c:3337:47: error: ‘TS_AUTOLOAD’ undeclared (first use in this function)
```
This is using the current `dev` branch @ c0af55a921c1

**Comment by cardigliano** [comment]
@sempervictus what distribution are you running? Please note we support only "LTS" kernels from Ubuntu, this does not look like one of the kernels we currently support

**Comment by gbravery** [comment]
I'm documenting this here, for interest as I saw similar issues.
NB I am on Debain, kernel 6.4.0-4 **AND** I am not a kernel person, I'm offering no support, just information!

That being said, for 6.4 I had to add one line and change another to make the module compile.
This was added to bottom of <linux/ ... > includes:
`#include <linux/textsearch.h>`
This basically made all the errors you state above vanish.

Change a line within do_memory_mmap:
Was:
`vma->vm_flags |= flags;`
Became:
`vm_flags_set(vma, flags);`
As vma.flags is now readonly, and this is the new method of changing flags.

As I said, your mileage may vary but it now adds to my kernel and the system hasn't crashed!
```
[619421.214511] pf_ring: loading out-of-tree module taints kernel.
[619421.214533] pf_ring: module verification failed: signature and/or required key missing - tainting kernel
[619421.217274] [PF_RING] Welcome to PF_RING 8.6.0 ($Revision: 8.6.0-stable:7ca3da72aa86556598fddf69157fe65b604a5bb0$)
                (C) 2004-22 ntop
[619421.217287] LINUX_VERSION_CODE 0006040D
[619421.217291] [PF_RING] Min # ring slots 4096
[619421.217294] [PF_RING] Slot version     20
[619421.217295] [PF_RING] Capture TX       Yes [RX+TX]
[619421.217297] [PF_RING] IP Defragment    No
[619421.217321] NET: Registered PF_IB protocol family
[619421.221497] [PF_RING] pf_ring initialized correctly
```

Just remember - no support, not a kernel person. _caveat emptor_

**Comment by gbravery** [comment]
FWIW, this patch makes a module that compiles for me.

NB - I copied the code in this patch by hand and replicated a similar fix for the include based on it before I saw your include change. So, I didn't remove <linux/pci.h> as you have in the include patch...
