### ISSUE TITLE
igb_main.c:7638:3: error: implicit declaration of function ‘read_barrier_depends’

### ISSUE THREAD

**Issue by jpds** [ntop/PF_RING#758]
The `igb` driver fails to build with an `5.13.13` source tree with:

```
PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc $ make
cd src; make
make[1]: Entering directory '/home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src'
# PF_RING
cd /home/user/tmp/PF_RING-8.0.0/kernel/; make
make[2]: Entering directory '/home/user/tmp/PF_RING-8.0.0/kernel'
which: no git in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
make -C /lib/modules/5.13.13-gentoo-dist/build M=/home/user/tmp/PF_RING-8.0.0/kernel EXTRA_CFLAGS='-I/home/user/tmp/PF_RING-8.0.0/kernel  -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[3]: Entering directory '/usr/src/linux-5.13.13-gentoo-dist'
which: no git in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
which: no git in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
make[3]: Leaving directory '/usr/src/linux-5.13.13-gentoo-dist'
make[2]: Leaving directory '/home/user/tmp/PF_RING-8.0.0/kernel'
cp /home/user/tmp/PF_RING-8.0.0/kernel/Module.symvers .
make[2]: Entering directory '/usr/src/linux-5.13.13-gentoo-dist'
  CC [M]  /home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src/igb_main.o
/home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src/igb_main.c: In function ‘igb_clean_tx_irq’:
/home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src/igb_main.c:7638:3: error: implicit declaration of function ‘read_barrier_depends’ [-Werror=implicit-function-declaration]
 7638 |   read_barrier_depends();
      |   ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:273: /home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src/igb_main.o] Error 1
make[2]: *** [Makefile:1862: /home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src] Error 2
make[2]: Leaving directory '/usr/src/linux-5.13.13-gentoo-dist'
make[1]: *** [Makefile:85: default] Error 2
make[1]: Leaving directory '/home/user/tmp/PF_RING-8.0.0/drivers/intel/igb/igb-5.3.5.18-zc/src'
make: *** [Makefile:5: all] Error 2
```

...which appears to have been deprecated: https://lkml.org/lkml/2020/6/30/886

**Comment by cardigliano** [comment]
@jpds please note that gentoo is not officially supported, however I will try to push a patch support newer kernels asap.

**Comment by cardigliano** [comment]
@jpds please check if latest code compiles for you

**Comment by jpds** [comment]
@cardigliano That fixed it for me, thank you
