### ISSUE TITLE
ixgbe-zc DMKS build failure for kernel 2.6.32-642.el6.x86_64 (RHEL 6.8)

### ISSUE THREAD

**Issue by utilitynerd** [ntop/PF_RING#96]
While upgrading to RHEL 6.8, the ixgbe-zc driver module failes to build:

```
Loading new ixgbe-zc-4.1.5.562 DKMS files...
Building for 2.6.32-642.el6.x86_64
Building initial module for 2.6.32-642.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-642.el6.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/4.1.5.562/build/make.log for more information.
warning: %post(ixgbe-zc-4.1.5.562-1dkms.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package ixgbe-zc-4.1.5.562-1dkms.noarch
```

```
DKMS make.log for ixgbe-zc-4.1.5.562 for kernel 2.6.32-642.el6.x86_64 (x86_64)
Wed May 11 17:57:26 PDT 2016
make -C /lib/modules/2.6.32-642.el6.x86_64/build SUBDIRS=/var/lib/dkms/ixgbe-zc/4.1.5.562/build modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-642.el6.x86_64'
  CC [M]  /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_main.o
In file included from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_osdep.h:38,
                 from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_type.h:66,
                 from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_dcb.h:28,
                 from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe.h:49,
                 from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_main.c:51:
/var/lib/dkms/ixgbe-zc/4.1.5.562/build/kcompat.h: In function ‘__kc_vlan_get_protocol’:
/var/lib/dkms/ixgbe-zc/4.1.5.562/build/kcompat.h:3404: error: implicit declaration of function ‘vlan_tx_tag_present’
In file included from /var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_main.c:51:
/var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe.h: In function ‘ixgbe_qv_unlock_napi’:
/var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe.h:602: error: too few arguments to function ‘napi_gro_flush’
make[2]: *** [/var/lib/dkms/ixgbe-zc/4.1.5.562/build/ixgbe_main.o] Error 1
make[1]: *** [_module_/var/lib/dkms/ixgbe-zc/4.1.5.562/build] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-642.el6.x86_64'
make: *** [default] Error 2
```

**Comment by cardigliano** [comment]
I patched the driver and new packages will be available in ~1h, however this is a blind fix (this is not one of the systems in our lab atm) thus it could require other fixes.
